import type { SeedMenu } from '../types';

/**
 * 중식(中食) 시드 레시피 풀 — RULES R9.
 * 모든 항목은 type:"home", cuisine:"CN". id는 안정적 슬러그(cn-*)로 유일하다.
 * 카테고리·단위·pantryStaple은 R4 코드와 1:1.
 */
export const cnSeed: SeedMenu[] = [
  {
    id: 'cn-jjajangmyeon',
    name: '짜장면',
    cuisine: 'CN',
    type: 'home',
    description: '춘장을 충분히 볶아 만든 한국식 중화요리의 대표 면 요리.',
    difficulty: 'medium',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 680,
    tags: ['면', '춘장', '돼지고기', '한국식중화'],
    recipe: {
      steps: [
        '1. 돼지고기와 양파·양배추·애호박을 한입 크기로 깍둑 썬다.',
        '2. 팬에 식용유를 넉넉히 두르고 춘장을 약불에서 3분간 볶아 기름장을 만든다.',
        '3. 다른 팬에 식용유를 두르고 돼지고기를 볶다가 채소를 넣어 숨이 죽을 때까지 볶는다.',
        '4. 볶은 춘장을 넣고 물 1.5컵과 설탕을 더해 끓인다.',
        '5. 전분물을 조금씩 풀어 원하는 농도로 걸쭉하게 맞춘다.',
        '6. 삶아 건진 중화면 위에 짜장 소스를 듬뿍 올려 낸다.',
      ],
      tips: [
        '춘장은 반드시 미리 볶아야 쓴맛이 사라지고 고소해진다.',
        '면은 삶은 뒤 찬물에 헹궈 전분기를 빼면 덜 붇는다.',
      ],
    },
    ingredients: [
      { name: '중화면', quantity: 300, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '돼지고기 앞다리살', quantity: 150, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양배추', quantity: 150, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '애호박', quantity: 0.5, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '춘장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '전분', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 4, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-jjamppong',
    name: '짬뽕',
    cuisine: 'CN',
    type: 'home',
    description: '고춧가루를 볶아 얼큰하게 끓인 해물 가득 매운 국물 면.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 620,
    tags: ['면', '해물', '매콤', '국물'],
    recipe: {
      steps: [
        '1. 오징어·홍합·새우 등 해물을 손질해 둔다.',
        '2. 양파·양배추·대파를 큼직하게 썬다.',
        '3. 달군 팬에 식용유와 고춧가루를 넣고 약불에서 볶아 고추기름을 낸다.',
        '4. 다진마늘과 채소를 넣어 센 불에 볶는다.',
        '5. 해물을 넣고 물 3컵을 부어 끓이며 간장·소금으로 간한다.',
        '6. 삶은 중화면을 그릇에 담고 뜨거운 국물을 부어 낸다.',
      ],
      tips: [
        '고춧가루는 태우지 않게 약불에서 볶아야 깔끔한 매운맛이 난다.',
        '해물은 마지막에 넣어 오래 끓이지 않아야 질겨지지 않는다.',
      ],
    },
    ingredients: [
      { name: '중화면', quantity: 300, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '오징어', quantity: 0.5, unit: '개', category: 'seafood', pantryStaple: false },
      { name: '홍합', quantity: 150, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '칵테일새우', quantity: 80, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '양파', quantity: 0.5, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양배추', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '고춧가루', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-mapa-dubu',
    name: '마파두부',
    cuisine: 'CN',
    type: 'home',
    description: '두반장과 두부로 만든 얼얼하고 매콤한 사천식 두부 요리.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 420,
    tags: ['두부', '사천', '매콤', '밥반찬'],
    recipe: {
      steps: [
        '1. 두부는 사방 2cm로 깍둑 썰어 끓는 소금물에 데친다.',
        '2. 팬에 식용유를 두르고 다진 돼지고기를 볶는다.',
        '3. 두반장과 다진마늘, 고춧가루를 넣어 함께 볶아 향을 낸다.',
        '4. 물 1컵과 간장·설탕을 넣고 끓인다.',
        '5. 데친 두부를 넣고 으깨지지 않게 살살 끓인다.',
        '6. 전분물로 농도를 맞추고 대파와 참기름을 더해 마무리한다.',
      ],
      tips: [
        '두부를 미리 데치면 부서지지 않고 간이 잘 밴다.',
        '산초가루를 약간 더하면 사천 특유의 얼얼한 맛이 산다.',
      ],
    },
    ingredients: [
      { name: '두부', quantity: 300, unit: 'g', category: 'etc', pantryStaple: false },
      { name: '다진 돼지고기', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '두반장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '고춧가루', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: false },
      { name: '대파', quantity: 0.5, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '전분', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-dongpa-yuk',
    name: '동파육',
    cuisine: 'CN',
    type: 'home',
    description: '삼겹살을 통째로 오래 조려 입에서 녹는 광둥식 돼지고기 찜.',
    difficulty: 'hard',
    cookTimeMin: 120,
    servings: 2,
    estimatedCalories: 780,
    tags: ['돼지고기', '삼겹살', '조림', '특별식'],
    recipe: {
      steps: [
        '1. 통삼겹살을 끓는 물에 10분 데쳐 잡내를 뺀다.',
        '2. 데친 삼겹살 표면을 노릇하게 지진다.',
        '3. 냄비에 대파·생강·삼겹살을 넣고 간장·설탕·청주를 붓는다.',
        '4. 물을 고기가 잠길 만큼 붓고 끓인 뒤 약불로 줄인다.',
        '5. 뚜껑을 덮고 1시간 30분 이상 뭉근히 조린다.',
        '6. 국물이 자작해지고 윤기가 나면 고기를 썰어 소스와 함께 낸다.',
      ],
      tips: [
        '약불에서 오래 조릴수록 비계가 젤리처럼 부드러워진다.',
        '데치는 과정을 생략하지 말아야 누린내가 잡힌다.',
      ],
    },
    ingredients: [
      { name: '통삼겹살', quantity: 500, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '생강', quantity: 2, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 5, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '청주', quantity: 4, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-kkanpung-gi',
    name: '깐풍기',
    cuisine: 'CN',
    type: 'home',
    description: '바삭하게 튀긴 닭을 매콤달콤한 마른 소스에 버무린 인기 요리.',
    difficulty: 'medium',
    cookTimeMin: 40,
    servings: 2,
    estimatedCalories: 590,
    tags: ['닭고기', '튀김', '매콤달콤', '한국식중화'],
    recipe: {
      steps: [
        '1. 닭다리살을 한입 크기로 썰어 청주·소금·후추로 밑간한다.',
        '2. 전분과 물, 달걀을 섞은 튀김옷을 입힌다.',
        '3. 170도 기름에 두 번 튀겨 바삭하게 만든다.',
        '4. 간장·식초·설탕·물을 섞어 깐풍 소스를 만든다.',
        '5. 팬에 다진마늘·건고추·대파를 볶아 향을 낸다.',
        '6. 소스를 부어 졸이다가 튀긴 닭을 넣고 빠르게 버무려 낸다.',
      ],
      tips: [
        '두 번 튀기면 소스에 버무려도 바삭함이 오래 유지된다.',
        '소스는 국물이 거의 없을 만큼 졸여야 깐풍 특유의 맛이 난다.',
      ],
    },
    ingredients: [
      { name: '닭다리살', quantity: 300, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '달걀', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '건고추', quantity: 3, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 0.5, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '전분', quantity: 5, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식초', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 3, unit: '컵', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-yurin-gi',
    name: '유린기',
    cuisine: 'CN',
    type: 'home',
    description: '바삭한 닭튀김 위에 새콤달콤 간장 소스와 채를 올린 요리.',
    difficulty: 'medium',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 560,
    tags: ['닭고기', '튀김', '새콤달콤', '한국식중화'],
    recipe: {
      steps: [
        '1. 닭가슴살을 넓게 펴 소금·후추·청주로 밑간한다.',
        '2. 전분을 묻혀 170도 기름에 바삭하게 튀긴다.',
        '3. 양파·대파·고추를 곱게 채 썬다.',
        '4. 간장·식초·설탕·물을 섞어 유린 소스를 만든다.',
        '5. 튀긴 닭을 먹기 좋게 썰어 접시에 담는다.',
        '6. 채소를 올리고 소스를 끼얹어 낸다.',
      ],
      tips: [
        '소스는 차갑게 준비해 튀김의 바삭함을 살린다.',
        '채소는 찬물에 담갔다 빼면 아삭함이 살아난다.',
      ],
    },
    ingredients: [
      { name: '닭가슴살', quantity: 300, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 0.5, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 0.5, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '청양고추', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '전분', quantity: 5, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식초', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 3, unit: '컵', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-menbosha',
    name: '멘보샤',
    cuisine: 'CN',
    type: 'home',
    description: '식빵 사이에 새우살을 넣고 튀긴 바삭한 중화 새우토스트.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 540,
    tags: ['새우', '튀김', '간식', '술안주'],
    recipe: {
      steps: [
        '1. 새우살을 칼로 다져 끈기가 생기도록 치댄다.',
        '2. 다진 새우에 소금·후추·전분·달걀흰자를 넣어 새우소를 만든다.',
        '3. 식빵의 가장자리를 잘라내고 두 장 사이에 새우소를 채운다.',
        '4. 네 등분으로 잘라 모양을 잡는다.',
        '5. 160도 기름에 노릇하게 튀긴다.',
        '6. 기름을 빼고 먹기 좋게 담아 낸다.',
      ],
      tips: [
        '기름 온도가 너무 높으면 속이 안 익으니 중온에서 천천히 튀긴다.',
        '새우소를 충분히 치대야 쫄깃한 식감이 난다.',
      ],
    },
    ingredients: [
      { name: '새우살', quantity: 200, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '식빵', quantity: 4, unit: '장', category: 'grain', pantryStaple: false },
      { name: '달걀', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '전분', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 3, unit: '컵', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-mala-xiangguo',
    name: '마라샹궈',
    cuisine: 'CN',
    type: 'home',
    description: '각종 재료를 마라 소스에 볶아낸 얼얼하고 매운 사천식 볶음.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 600,
    tags: ['마라', '사천', '매콤', '볶음'],
    recipe: {
      steps: [
        '1. 청경채·연근·버섯·감자를 한입 크기로 썰어 살짝 데친다.',
        '2. 소고기와 어묵, 소시지도 먹기 좋게 썬다.',
        '3. 팬에 식용유를 두르고 마라 소스와 건고추·화자오를 볶아 향을 낸다.',
        '4. 다진마늘과 소고기를 넣어 볶는다.',
        '5. 데친 채소와 나머지 재료를 넣고 센 불에 빠르게 볶는다.',
        '6. 간장과 설탕으로 간하고 고루 버무려 낸다.',
      ],
      tips: [
        '재료는 익는 시간이 다르므로 단단한 것부터 순서대로 넣는다.',
        '마라 소스 양으로 매운 정도를 조절한다.',
      ],
    },
    ingredients: [
      { name: '소고기 불고기감', quantity: 150, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '청경채', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '연근', quantity: 80, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '새송이버섯', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '어묵', quantity: 100, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '마라 소스', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '건고추', quantity: 4, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-saewu-bokkeumbap',
    name: '새우볶음밥',
    cuisine: 'CN',
    type: 'home',
    description: '고슬한 밥과 새우를 센 불에 볶아 고소하게 완성한 볶음밥.',
    difficulty: 'easy',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 560,
    tags: ['볶음밥', '새우', '간편', '한그릇'],
    recipe: {
      steps: [
        '1. 찬밥을 준비하고 달걀은 풀어 둔다.',
        '2. 대파와 당근을 잘게 다진다.',
        '3. 팬에 식용유를 두르고 달걀을 스크램블해 덜어 둔다.',
        '4. 다진마늘과 새우, 채소를 넣어 센 불에 볶는다.',
        '5. 밥을 넣고 눌러가며 고슬하게 볶는다.',
        '6. 달걀을 다시 넣고 간장·소금·후추로 간해 마무리한다.',
      ],
      tips: [
        '찬밥을 쓰면 밥알이 뭉치지 않고 고슬하게 볶인다.',
        '센 불에서 빠르게 볶아야 불맛이 살아난다.',
      ],
    },
    ingredients: [
      { name: '밥', quantity: 400, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '칵테일새우', quantity: 120, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '달걀', quantity: 2, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '대파', quantity: 0.5, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 0.3, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-chili-saewu',
    name: '칠리새우',
    cuisine: 'CN',
    type: 'home',
    description: '튀긴 새우를 매콤달콤한 칠리 소스에 버무린 인기 요리.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 520,
    tags: ['새우', '튀김', '매콤달콤', '한국식중화'],
    recipe: {
      steps: [
        '1. 새우를 손질해 소금·후추·청주로 밑간한다.',
        '2. 전분을 묻혀 170도 기름에 바삭하게 튀긴다.',
        '3. 케첩·고추기름·설탕·물을 섞어 칠리 소스를 만든다.',
        '4. 팬에 다진마늘과 양파를 볶아 향을 낸다.',
        '5. 소스를 넣고 끓이다가 전분물로 농도를 맞춘다.',
        '6. 튀긴 새우를 넣고 빠르게 버무려 낸다.',
      ],
      tips: [
        '소스 농도는 전분물로 천천히 맞춰 새우에 잘 입혀지게 한다.',
        '고추기름 양으로 매운맛을 조절한다.',
      ],
    },
    ingredients: [
      { name: '새우', quantity: 250, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '양파', quantity: 0.5, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '케첩', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '고추기름', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '전분', quantity: 4, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 3, unit: '컵', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-tangsuyuk',
    name: '탕수육',
    cuisine: 'CN',
    type: 'home',
    description: '바삭한 돼지고기 튀김에 새콤달콤 탕수 소스를 곁들인 국민 메뉴.',
    difficulty: 'medium',
    cookTimeMin: 45,
    servings: 2,
    estimatedCalories: 720,
    tags: ['돼지고기', '튀김', '새콤달콤', '한국식중화'],
    recipe: {
      steps: [
        '1. 돼지등심을 길게 썰어 소금·후추·청주로 밑간한다.',
        '2. 전분과 물을 섞어 30분 두었다가 튀김옷을 만든다.',
        '3. 고기에 튀김옷을 입혀 170도에서 두 번 튀긴다.',
        '4. 당근·양파·목이버섯을 썰어 둔다.',
        '5. 물·설탕·식초·간장을 끓이고 채소를 넣는다.',
        '6. 전분물로 농도를 맞춘 소스를 튀김 위에 끼얹어 낸다.',
      ],
      tips: [
        '튀김옷 전분물은 가라앉힌 뒤 윗물을 따라내고 되직하게 쓴다.',
        '두 번 튀겨야 소스를 부어도 바삭함이 유지된다.',
      ],
    },
    ingredients: [
      { name: '돼지등심', quantity: 300, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '당근', quantity: 0.3, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 0.5, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '목이버섯', quantity: 20, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '전분', quantity: 1, unit: '컵', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 4, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식초', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 4, unit: '컵', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-gwobaru',
    name: '꿔바로우',
    cuisine: 'CN',
    type: 'home',
    description: '찹쌀 전분옷을 입혀 더 바삭하게 튀긴 동북식 탕수육.',
    difficulty: 'hard',
    cookTimeMin: 50,
    servings: 2,
    estimatedCalories: 750,
    tags: ['돼지고기', '튀김', '새콤달콤', '바삭'],
    recipe: {
      steps: [
        '1. 돼지등심을 넓고 얇게 저며 소금·청주로 밑간한다.',
        '2. 찹쌀전분과 물을 섞어 되직한 튀김옷을 만든다.',
        '3. 고기에 튀김옷을 입혀 170도에서 바삭하게 튀긴다.',
        '4. 한 김 식힌 뒤 한 번 더 튀겨 바삭함을 살린다.',
        '5. 설탕·식초·간장·물을 끓여 새콤달콤 소스를 만든다.',
        '6. 튀긴 고기를 소스에 빠르게 버무리고 고수와 생강채를 올려 낸다.',
      ],
      tips: [
        '찹쌀전분을 쓰면 일반 탕수육보다 훨씬 바삭하다.',
        '소스에 버무린 뒤 바로 먹어야 바삭함이 살아 있다.',
      ],
    },
    ingredients: [
      { name: '돼지등심', quantity: 300, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '찹쌀전분', quantity: 1, unit: '컵', category: 'seasoning', pantryStaple: false },
      { name: '생강', quantity: 1, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '고수', quantity: 20, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '설탕', quantity: 4, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식초', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 4, unit: '컵', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-gochu-japchae',
    name: '고추잡채',
    cuisine: 'CN',
    type: 'home',
    description: '피망과 돼지고기를 가늘게 채 썰어 볶은 꽃빵과 잘 어울리는 요리.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 380,
    tags: ['돼지고기', '피망', '볶음', '꽃빵'],
    recipe: {
      steps: [
        '1. 돼지고기를 가늘게 채 썰어 간장·청주·전분으로 밑간한다.',
        '2. 피망·양파·죽순을 가늘게 채 썬다.',
        '3. 팬에 식용유를 두르고 돼지고기를 볶아 덜어 둔다.',
        '4. 같은 팬에 다진마늘과 채소를 넣어 센 불에 볶는다.',
        '5. 볶은 고기를 다시 넣고 굴소스·간장으로 간한다.',
        '6. 참기름을 둘러 마무리하고 찐 꽃빵과 함께 낸다.',
      ],
      tips: [
        '채소는 센 불에 짧게 볶아야 아삭함이 유지된다.',
        '재료를 모두 비슷한 굵기로 채 썰면 보기도 좋고 식감도 고르다.',
      ],
    },
    ingredients: [
      { name: '돼지고기 등심', quantity: 150, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '피망', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 0.5, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '죽순', quantity: 80, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '꽃빵', quantity: 4, unit: '개', category: 'grain', pantryStaple: false },
      { name: '굴소스', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-palbochae',
    name: '팔보채',
    cuisine: 'CN',
    type: 'home',
    description: '여러 해물과 채소를 굴소스에 볶아낸 화려한 잔치 요리.',
    difficulty: 'hard',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 480,
    tags: ['해물', '볶음', '굴소스', '특별식'],
    recipe: {
      steps: [
        '1. 오징어·새우·해삼 등 해물을 손질해 데친다.',
        '2. 청경채·표고버섯·죽순·당근을 먹기 좋게 썬다.',
        '3. 팬에 식용유를 두르고 다진마늘과 생강을 볶는다.',
        '4. 채소를 넣어 센 불에 볶다가 해물을 넣는다.',
        '5. 굴소스·간장·청주와 물 0.5컵을 넣어 끓인다.',
        '6. 전분물로 농도를 맞추고 참기름을 둘러 낸다.',
      ],
      tips: [
        '해물은 미리 데쳐 두면 볶을 때 물이 생기지 않는다.',
        '센 불에서 단시간에 볶아야 재료가 질겨지지 않는다.',
      ],
    },
    ingredients: [
      { name: '오징어', quantity: 0.5, unit: '개', category: 'seafood', pantryStaple: false },
      { name: '칵테일새우', quantity: 100, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '해삼', quantity: 80, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '청경채', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '표고버섯', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '죽순', quantity: 60, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '굴소스', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '전분', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-rajogi',
    name: '라조기',
    cuisine: 'CN',
    type: 'home',
    description: '튀긴 닭과 채소를 매콤한 라조 소스에 볶아 걸쭉하게 끓인 요리.',
    difficulty: 'medium',
    cookTimeMin: 40,
    servings: 2,
    estimatedCalories: 610,
    tags: ['닭고기', '튀김', '매콤', '국물자작'],
    recipe: {
      steps: [
        '1. 닭다리살을 큼직하게 썰어 청주·소금으로 밑간한다.',
        '2. 전분옷을 입혀 170도 기름에 바삭하게 튀긴다.',
        '3. 양파·죽순·청경채·건고추를 썬다.',
        '4. 팬에 식용유와 두반장을 볶아 매운 향을 낸다.',
        '5. 채소를 넣어 볶고 물 1컵과 간장·설탕을 넣어 끓인다.',
        '6. 튀긴 닭을 넣고 전분물로 농도를 맞춰 자작하게 끓여 낸다.',
      ],
      tips: [
        '두반장을 볶아 매운 향을 낸 뒤 국물을 잡으면 깊은 맛이 난다.',
        '닭은 마지막에 넣어 바삭함과 부드러움을 함께 살린다.',
      ],
    },
    ingredients: [
      { name: '닭다리살', quantity: 300, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 0.5, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '죽순', quantity: 60, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '청경채', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '건고추', quantity: 3, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '두반장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '전분', quantity: 5, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 3, unit: '컵', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-mala-tang',
    name: '마라탕',
    cuisine: 'CN',
    type: 'home',
    description: '좋아하는 재료를 골라 얼얼한 마라 육수에 끓여 먹는 사천식 탕.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 450,
    tags: ['마라', '국물', '매콤', '한그릇'],
    recipe: {
      steps: [
        '1. 청경채·배추·버섯·숙주를 씻어 손질한다.',
        '2. 분모자(당면)는 미리 물에 불려 둔다.',
        '3. 냄비에 물을 붓고 마라탕 소스를 풀어 끓인다.',
        '4. 어묵·소고기·두부 등 단단한 재료부터 넣고 끓인다.',
        '5. 채소와 불린 분모자를 넣어 익힌다.',
        '6. 간을 보고 그릇에 담아 고수를 올려 낸다.',
      ],
      tips: [
        '분모자는 미리 불려야 끓일 때 빨리 익는다.',
        '마라탕 소스 양으로 맵기와 얼얼함을 조절한다.',
      ],
    },
    ingredients: [
      { name: '소고기 샤브샤브용', quantity: 120, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '분모자', quantity: 80, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '청경채', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '배추', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '팽이버섯', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '어묵', quantity: 80, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '마라탕 소스', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '고수', quantity: 15, unit: 'g', category: 'vegetable', pantryStaple: false },
    ],
  },
  {
    id: 'cn-gungbo-gijeong',
    name: '궁보계정',
    cuisine: 'CN',
    type: 'home',
    description: '닭고기와 땅콩을 매콤새콤한 소스에 볶은 사천식 쿵파오 치킨.',
    difficulty: 'medium',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 520,
    tags: ['닭고기', '땅콩', '사천', '볶음'],
    recipe: {
      steps: [
        '1. 닭다리살을 깍둑 썰어 간장·청주·전분으로 밑간한다.',
        '2. 간장·식초·설탕·전분·물을 섞어 소스를 만든다.',
        '3. 팬에 식용유를 두르고 건고추와 화자오를 볶아 향을 낸다.',
        '4. 닭고기를 넣고 겉면이 익을 때까지 볶는다.',
        '5. 대파와 소스를 넣어 빠르게 볶아 농도를 낸다.',
        '6. 볶은 땅콩을 넣고 한 번 더 섞어 낸다.',
      ],
      tips: [
        '땅콩은 마지막에 넣어야 바삭함이 살아 있다.',
        '소스를 미리 만들어 두면 센 불에서 빠르게 볶을 수 있다.',
      ],
    },
    ingredients: [
      { name: '닭다리살', quantity: 300, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '볶은 땅콩', quantity: 50, unit: 'g', category: 'etc', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '건고추', quantity: 4, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식초', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '전분', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-eohyang-gaji',
    name: '어향가지',
    cuisine: 'CN',
    type: 'home',
    description: '튀긴 가지를 매콤달콤한 어향 소스에 볶은 밥도둑 사천 요리.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 400,
    tags: ['가지', '사천', '매콤달콤', '밥반찬'],
    recipe: {
      steps: [
        '1. 가지를 큼직하게 썰어 전분을 가볍게 묻힌다.',
        '2. 기름에 가지를 노릇하게 튀기듯 볶아 덜어 둔다.',
        '3. 다진 돼지고기를 볶다가 두반장·다진마늘을 넣는다.',
        '4. 간장·설탕·식초·물을 넣어 어향 소스를 끓인다.',
        '5. 튀긴 가지를 넣어 소스가 배도록 볶는다.',
        '6. 전분물로 농도를 맞추고 대파를 넣어 마무리한다.',
      ],
      tips: [
        '가지에 전분을 살짝 묻혀 볶으면 기름 흡수가 줄고 식감이 좋다.',
        '어향 소스는 단맛·신맛·매운맛의 균형이 핵심이다.',
      ],
    },
    ingredients: [
      { name: '가지', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '다진 돼지고기', quantity: 80, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '대파', quantity: 0.5, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '두반장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식초', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '전분', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 4, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-tomato-gyeran',
    name: '토마토계란볶음',
    cuisine: 'CN',
    type: 'home',
    description: '토마토와 부드러운 달걀을 함께 볶은 중국 가정식 대표 요리.',
    difficulty: 'easy',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 300,
    tags: ['달걀', '토마토', '간편', '가정식'],
    recipe: {
      steps: [
        '1. 토마토를 큼직하게 썰고 대파는 송송 썬다.',
        '2. 달걀을 풀어 소금으로 가볍게 간한다.',
        '3. 팬에 식용유를 두르고 달걀을 반숙으로 볶아 덜어 둔다.',
        '4. 같은 팬에 토마토를 넣어 즙이 나올 때까지 볶는다.',
        '5. 설탕·소금으로 간하고 볶은 달걀을 다시 넣는다.',
        '6. 가볍게 섞고 대파를 올려 마무리한다.',
      ],
      tips: [
        '달걀은 반숙으로 먼저 익혀 두면 부드러운 식감을 살릴 수 있다.',
        '설탕을 약간 넣으면 토마토의 신맛이 부드러워진다.',
      ],
    },
    ingredients: [
      { name: '토마토', quantity: 2, unit: '개', category: 'fruit', pantryStaple: false },
      { name: '달걀', quantity: 3, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '대파', quantity: 0.5, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '설탕', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-wuyu-myeon',
    name: '우육면',
    cuisine: 'CN',
    type: 'home',
    description: '소고기와 향신료로 오래 끓인 진한 국물의 대만식 소고기 국수.',
    difficulty: 'hard',
    cookTimeMin: 90,
    servings: 2,
    estimatedCalories: 640,
    tags: ['소고기', '면', '국물', '대만식'],
    recipe: {
      steps: [
        '1. 소고기 사태를 끓는 물에 데쳐 핏물을 뺀다.',
        '2. 팬에 두반장·다진마늘·생강을 볶아 향을 낸다.',
        '3. 데친 소고기와 간장·설탕·청주를 넣어 함께 볶는다.',
        '4. 물 5컵과 팔각·대파를 넣고 끓인다.',
        '5. 약불로 1시간 이상 끓여 고기를 부드럽게 익힌다.',
        '6. 삶은 면을 그릇에 담고 고기와 국물을 부어 청경채를 올려 낸다.',
      ],
      tips: [
        '사태는 오래 끓일수록 부드럽고 국물이 진해진다.',
        '팔각 한 알이면 충분하니 너무 많이 넣지 않는다.',
      ],
    },
    ingredients: [
      { name: '소고기 사태', quantity: 400, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '중화면', quantity: 300, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '청경채', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '생강', quantity: 2, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '팔각', quantity: 1, unit: '개', category: 'seasoning', pantryStaple: false },
      { name: '두반장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-hoegwayuk',
    name: '회과육',
    cuisine: 'CN',
    type: 'home',
    description: '삶은 삼겹살을 두반장에 다시 볶아낸 사천식 두 번 익힌 돼지고기.',
    difficulty: 'medium',
    cookTimeMin: 40,
    servings: 2,
    estimatedCalories: 660,
    tags: ['돼지고기', '삼겹살', '사천', '볶음'],
    recipe: {
      steps: [
        '1. 통삼겹살을 대파·생강과 함께 20분 삶는다.',
        '2. 삶은 고기를 식혀 0.5cm 두께로 얇게 썬다.',
        '3. 양배추·대파·피망을 큼직하게 썬다.',
        '4. 팬에 식용유를 두르고 삼겹살을 노릇하게 볶는다.',
        '5. 두반장·다진마늘·설탕을 넣어 함께 볶는다.',
        '6. 채소를 넣고 센 불에 빠르게 볶아 간장으로 마무리한다.',
      ],
      tips: [
        '삼겹살은 한 번 삶아 기름기를 빼면 느끼하지 않다.',
        '두반장을 충분히 볶아야 매콤한 향이 깊어진다.',
      ],
    },
    ingredients: [
      { name: '통삼겹살', quantity: 300, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양배추', quantity: 150, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '피망', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '생강', quantity: 1, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '두반장', quantity: 1.5, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-wantang-myeon',
    name: '완탕면',
    cuisine: 'CN',
    type: 'home',
    description: '새우완탕을 맑은 국물에 띄운 광둥식 면 요리.',
    difficulty: 'medium',
    cookTimeMin: 40,
    servings: 2,
    estimatedCalories: 480,
    tags: ['면', '완탕', '국물', '새우'],
    recipe: {
      steps: [
        '1. 다진 새우살과 돼지고기에 소금·후추·참기름을 넣어 소를 만든다.',
        '2. 완탕피에 소를 한 숟갈씩 넣고 감싸 빚는다.',
        '3. 냄비에 물을 붓고 대파·생강을 넣어 맑은 육수를 끓인다.',
        '4. 간장·소금으로 육수 간을 맞춘다.',
        '5. 빚은 완탕과 중화면을 끓는 물에 삶는다.',
        '6. 그릇에 면과 완탕을 담고 육수를 부어 청경채를 올려 낸다.',
      ],
      tips: [
        '완탕은 끓는 물에 떠오르면 다 익은 것이다.',
        '육수는 맑게 끓여야 완탕 본연의 맛이 산다.',
      ],
    },
    ingredients: [
      { name: '완탕피', quantity: 16, unit: '장', category: 'grain', pantryStaple: false },
      { name: '새우살', quantity: 100, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '다진 돼지고기', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '중화면', quantity: 200, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '청경채', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '생강', quantity: 1, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-yangkkochi',
    name: '양꼬치',
    cuisine: 'CN',
    type: 'home',
    description: '양고기를 꼬치에 꿰어 쯔란을 뿌려 구운 중국 동북식 길거리 요리.',
    difficulty: 'easy',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 540,
    tags: ['양고기', '꼬치', '구이', '술안주'],
    recipe: {
      steps: [
        '1. 양고기를 한입 크기로 썰어 청주·소금·후추로 밑간한다.',
        '2. 밑간한 고기를 꼬치에 꿴다.',
        '3. 달군 팬이나 그릴에 식용유를 살짝 두른다.',
        '4. 꼬치를 올려 앞뒤로 노릇하게 굽는다.',
        '5. 쯔란과 고춧가루를 고기 위에 뿌린다.',
        '6. 한 번 더 뒤집어 향을 입히고 접시에 담아 낸다.',
      ],
      tips: [
        '쯔란은 구이 마지막에 뿌려야 향이 날아가지 않는다.',
        '센 불에 겉을 빠르게 익혀야 육즙이 갇힌다.',
      ],
    },
    ingredients: [
      { name: '양고기', quantity: 400, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '쯔란', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '고춧가루', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '청주', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-ulmyeon',
    name: '울면',
    cuisine: 'CN',
    type: 'home',
    description: '해물과 채소를 넣고 전분으로 걸쭉하게 끓인 부드러운 중화 면 요리.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 500,
    tags: ['면', '해물', '국물', '걸쭉'],
    recipe: {
      steps: [
        '1. 오징어·새우·홍합을 손질하고 채소를 채 썬다.',
        '2. 냄비에 물 4컵을 붓고 대파·다진마늘을 넣어 끓인다.',
        '3. 해물과 채소를 넣어 익힌다.',
        '4. 간장·소금으로 간을 맞춘다.',
        '5. 전분물을 풀어 걸쭉하게 농도를 낸다.',
        '6. 풀어 둔 달걀을 줄알처럼 둘러 넣고 삶은 면 위에 부어 낸다.',
      ],
      tips: [
        '전분물은 끓는 상태에서 조금씩 넣어야 뭉치지 않는다.',
        '달걀은 불을 약하게 한 뒤 천천히 풀어야 곱게 퍼진다.',
      ],
    },
    ingredients: [
      { name: '중화면', quantity: 300, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '오징어', quantity: 0.5, unit: '개', category: 'seafood', pantryStaple: false },
      { name: '칵테일새우', quantity: 80, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '달걀', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '양파', quantity: 0.5, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '전분', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'cn-ganjjajang',
    name: '간짜장',
    cuisine: 'CN',
    type: 'home',
    description: '물전분 없이 춘장을 즉석에서 볶아 면에 비벼 먹는 진한 짜장.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 700,
    tags: ['면', '춘장', '돼지고기', '한국식중화'],
    recipe: {
      steps: [
        '1. 양파를 큼직하게 썰고 돼지고기는 깍둑 썬다.',
        '2. 팬에 식용유를 넉넉히 두르고 춘장을 약불에서 볶아 둔다.',
        '3. 다른 팬에 돼지고기를 볶다가 양파를 넣어 볶는다.',
        '4. 볶은 춘장을 넣고 설탕을 더해 센 불에 함께 볶는다.',
        '5. 물을 아주 조금만 넣어 되직한 농도로 졸인다.',
        '6. 삶은 면 위에 즉석에서 볶은 짜장을 부어 비벼 먹는다.',
      ],
      tips: [
        '간짜장은 물전분을 쓰지 않아 일반 짜장보다 진하고 고소하다.',
        '주문 즉시 볶아 내듯 빠르게 볶아야 불맛이 산다.',
      ],
    },
    ingredients: [
      { name: '중화면', quantity: 300, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '돼지고기 앞다리살', quantity: 150, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1.5, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '애호박', quantity: 0.3, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '춘장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 5, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
];
