import type { SeedMenu } from '../types';

/**
 * 외식 시드 풀 — RULES R9 / R2 (type:"dineout").
 * 레시피·재료 없음. 각 항목은 안정적 슬러그 id(dineout-*)와 외부 검색 키워드를 가진다.
 * 매 슬롯 기본 1개 포함되는 외식 선지의 1차 출처(R1-2, R1-7).
 */
export const dineoutSeed: SeedMenu[] = [
  {
    id: 'dineout-gukbap',
    name: '동네 국밥집 돼지국밥',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '뜨끈하게 한 그릇 비우기 좋은 든든한 한 끼',
    tags: ['한식계열', '국물', '든든'],
    searchKeyword: '돼지국밥 맛집',
  },
  {
    id: 'dineout-samgyeopsal',
    name: '근처 고깃집 삼겹살',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '여럿이 둘러앉아 굽기 좋은 회식 단골 메뉴',
    tags: ['한식계열', '구이', '회식'],
    searchKeyword: '삼겹살 맛집',
  },
  {
    id: 'dineout-kalguksu',
    name: '손칼국수 전문점 칼국수',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '쫄깃한 면에 시원한 국물이 어울리는 점심',
    tags: ['한식계열', '면', '국물'],
    searchKeyword: '손칼국수 맛집',
  },
  {
    id: 'dineout-bossam',
    name: '보쌈집 모둠보쌈',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '부드러운 수육과 김치를 곁들여 먹는 푸짐한 한상',
    tags: ['한식계열', '수육', '든든'],
    searchKeyword: '보쌈 맛집',
  },
  {
    id: 'dineout-jjajangmyeon',
    name: '중국집 짜장면',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '간편하게 배달로 즐기는 국민 외식 메뉴',
    tags: ['중식계열', '면', '배달'],
    searchKeyword: '짜장면 맛집',
  },
  {
    id: 'dineout-tangsuyuk',
    name: '중국집 탕수육',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '바삭한 튀김에 새콤달콤 소스를 곁들인 인기 요리',
    tags: ['중식계열', '튀김', '배달'],
    searchKeyword: '탕수육 맛집',
  },
  {
    id: 'dineout-mapotofu',
    name: '마라 전문점 마파두부덮밥',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '알싸하고 얼얼한 맛으로 입맛 돋우는 한 그릇',
    tags: ['중식계열', '덮밥', '매콤'],
    searchKeyword: '마파두부 맛집',
  },
  {
    id: 'dineout-sushi',
    name: '동네 초밥집 모둠초밥',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '가볍게 사먹기 좋은 신선한 점심',
    tags: ['일식계열', '간편'],
    searchKeyword: '초밥 맛집',
  },
  {
    id: 'dineout-ramen',
    name: '라멘 전문점 돈코츠라멘',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '진한 국물과 쫄깃한 면이 어울리는 일본식 한 끼',
    tags: ['일식계열', '면', '국물'],
    searchKeyword: '라멘 맛집',
  },
  {
    id: 'dineout-tonkatsu',
    name: '경양식 돈카츠집 등심돈카츠',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '두툼하게 튀겨낸 바삭한 돈카츠 정식',
    tags: ['일식계열', '튀김', '든든'],
    searchKeyword: '돈카츠 맛집',
  },
  {
    id: 'dineout-pasta',
    name: '동네 파스타집 토마토파스타',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '분위기 내며 가볍게 즐기기 좋은 양식 한 끼',
    tags: ['양식계열', '면', '간편'],
    searchKeyword: '파스타 맛집',
  },
  {
    id: 'dineout-burger',
    name: '수제버거집 치즈버거',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '두툼한 패티로 든든하게 한 끼 해결',
    tags: ['양식계열', '간편', '든든'],
    searchKeyword: '수제버거 맛집',
  },
  {
    id: 'dineout-pizza',
    name: '화덕피자집 마르게리타피자',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '여럿이 나눠 먹기 좋은 배달·포장 단골 메뉴',
    tags: ['양식계열', '배달', '나눠먹기'],
    searchKeyword: '화덕피자 맛집',
  },
  {
    id: 'dineout-tteokbokki',
    name: '분식집 떡볶이 세트',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '매콤달콤 떡볶이에 튀김·순대를 곁들인 분식 한상',
    tags: ['분식', '매콤', '간편'],
    searchKeyword: '떡볶이 맛집',
  },
  {
    id: 'dineout-chicken',
    name: '치킨집 후라이드치킨',
    cuisine: 'DINEOUT',
    type: 'dineout',
    description: '간편하게 배달로 즐기는 야식·회식 인기 메뉴',
    tags: ['치킨', '튀김', '배달'],
    searchKeyword: '치킨 맛집',
  },
];
