import type { SeedMenu } from '../types';

/**
 * 일식(JP) 시드 레시피 풀 — RULES R9.
 * 모든 항목은 type:"home", cuisine:"JP". id는 jp- 접두 안정 슬러그(유일).
 * 단위/카테고리/pantryStaple은 R4 코드와 1:1. 사용자 노출 텍스트는 한국어.
 */
export const jpSeed: SeedMenu[] = [
  {
    id: 'jp-gyudon',
    name: '규동 (소고기덮밥)',
    cuisine: 'JP',
    type: 'home',
    description: '달콤짭짤하게 졸인 소고기와 양파를 밥에 듬뿍 올린 일본식 덮밥.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 680,
    tags: ['덮밥', '소고기', '간편', '한그릇'],
    recipe: {
      steps: [
        '1. 양파는 결대로 얇게 채 썰고, 소고기는 한입 크기로 준비한다.',
        '2. 냄비에 물 1컵, 간장, 미림, 설탕을 넣고 끓여 양념장을 만든다.',
        '3. 끓는 양념에 양파를 넣고 부드러워질 때까지 5분간 졸인다.',
        '4. 소고기를 넣고 핏기가 사라질 때까지 익히며 거품을 걷어낸다.',
        '5. 국물이 자작해지면 따뜻한 밥 위에 국물째 올린다.',
        '6. 쪽파와 베니쇼가(생강초절임)를 곁들여 완성한다.',
      ],
      tips: [
        '날달걀이나 반숙 온천란을 올리면 더 부드럽게 즐길 수 있다.',
        '국물을 살짝 남겨 밥에 스미게 하면 풍미가 좋다.',
      ],
    },
    ingredients: [
      { name: '소고기 불고기감', quantity: 250, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '쪽파', quantity: 2, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '미림', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '밥', quantity: 2, unit: '컵', category: 'grain', pantryStaple: false },
    ],
  },
  {
    id: 'jp-katsudon',
    name: '가츠동 (돈카츠덮밥)',
    cuisine: 'JP',
    type: 'home',
    description: '바삭한 돈카츠를 달짝지근한 양념과 달걀로 감싸 밥에 올린 덮밥.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 820,
    tags: ['덮밥', '돼지고기', '달걀', '한그릇'],
    recipe: {
      steps: [
        '1. 돈카츠는 미리 튀기거나 시판 제품을 데워 한입 크기로 썬다.',
        '2. 작은 팬에 물 반 컵, 간장, 미림, 설탕을 넣고 끓인다.',
        '3. 채 썬 양파를 넣고 투명해질 때까지 끓인다.',
        '4. 썰어둔 돈카츠를 올리고 풀어둔 달걀의 절반을 둘러 붓는다.',
        '5. 남은 달걀을 마저 붓고 뚜껑을 덮어 반숙으로 익힌다.',
        '6. 밥 위에 국물째 슬라이드하듯 올리고 쪽파를 뿌린다.',
      ],
      tips: [
        '달걀은 완전히 익히지 말고 반숙으로 마무리해야 촉촉하다.',
        '한 그릇씩 따로 만들면 모양이 흐트러지지 않는다.',
      ],
    },
    ingredients: [
      { name: '돈카츠', quantity: 2, unit: '장', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '달걀', quantity: 4, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '쪽파', quantity: 2, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '미림', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '밥', quantity: 2, unit: '컵', category: 'grain', pantryStaple: false },
    ],
  },
  {
    id: 'jp-oyakodon',
    name: '오야코동 (닭고기달걀덮밥)',
    cuisine: 'JP',
    type: 'home',
    description: '닭고기와 달걀을 함께 졸여 부드럽게 밥에 올린 가정식 덮밥.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 620,
    tags: ['덮밥', '닭고기', '달걀', '한그릇'],
    recipe: {
      steps: [
        '1. 닭다리살은 한입 크기로 썰고 양파는 채 썬다.',
        '2. 팬에 물 반 컵, 간장, 미림, 설탕을 넣고 끓인다.',
        '3. 양파와 닭고기를 넣고 닭이 익을 때까지 졸인다.',
        '4. 풀어둔 달걀의 2/3를 둘러 붓고 살짝 익힌다.',
        '5. 남은 달걀을 마저 부어 반숙 상태에서 불을 끈다.',
        '6. 따뜻한 밥에 올리고 쪽파와 김을 뿌려 완성한다.',
      ],
      tips: [
        '오야코(부모자식)라는 이름처럼 닭과 달걀을 함께 쓰는 것이 포인트다.',
        '미츠바나 쪽파를 마지막에 올리면 향이 산다.',
      ],
    },
    ingredients: [
      { name: '닭다리살', quantity: 250, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '달걀', quantity: 4, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '쪽파', quantity: 2, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '미림', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '밥', quantity: 2, unit: '컵', category: 'grain', pantryStaple: false },
    ],
  },
  {
    id: 'jp-tonkatsu',
    name: '돈카츠',
    cuisine: 'JP',
    type: 'home',
    description: '두툼한 등심에 빵가루를 입혀 바삭하게 튀긴 일본식 돈가스.',
    difficulty: 'medium',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 750,
    tags: ['튀김', '돼지고기', '바삭'],
    recipe: {
      steps: [
        '1. 돼지등심은 칼집을 내 연육하고 소금, 후추로 밑간한다.',
        '2. 밀가루, 푼 달걀, 빵가루 순으로 옷을 입힌다.',
        '3. 빵가루를 꾹 눌러 고르게 밀착시킨다.',
        '4. 170도 기름에 넣고 노릇해질 때까지 4~5분 튀긴다.',
        '5. 한 번 뒤집어 양면을 고루 익히고 건져 기름을 뺀다.',
        '6. 먹기 좋게 썰어 채 썬 양배추와 돈카츠 소스를 곁들인다.',
      ],
      tips: [
        '튀긴 뒤 5분간 세워서 기름을 빼면 바삭함이 오래간다.',
        '기름 온도는 빵가루를 떨어뜨려 바로 떠오르면 적당하다.',
      ],
    },
    ingredients: [
      { name: '돼지등심', quantity: 2, unit: '장', category: 'meat', pantryStaple: false },
      { name: '양배추', quantity: 200, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '밀가루', quantity: 4, unit: '큰술', category: 'grain', pantryStaple: true },
      { name: '달걀', quantity: 2, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '빵가루', quantity: 2, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '돈카츠 소스', quantity: 4, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 3, unit: '컵', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-karaage',
    name: '가라아게 (일본식 닭튀김)',
    cuisine: 'JP',
    type: 'home',
    description: '간장과 생강에 재운 닭다리살을 바삭하게 튀긴 인기 일식 메뉴.',
    difficulty: 'easy',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 590,
    tags: ['튀김', '닭고기', '안주', '바삭'],
    recipe: {
      steps: [
        '1. 닭다리살을 한입 크기로 썬다.',
        '2. 간장, 미림, 다진 마늘, 다진 생강을 넣고 20분 재운다.',
        '3. 재운 닭에 감자전분을 골고루 묻힌다.',
        '4. 170도 기름에 넣고 1차로 3분간 튀겨 건진다.',
        '5. 잠시 쉰 뒤 180도에서 1분간 한 번 더 튀긴다.',
        '6. 기름을 빼고 레몬을 곁들여 낸다.',
      ],
      tips: [
        '두 번 튀기면 속은 촉촉하고 겉은 더 바삭해진다.',
        '전분은 튀기기 직전에 묻혀야 옷이 눅눅해지지 않는다.',
      ],
    },
    ingredients: [
      { name: '닭다리살', quantity: 400, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '감자전분', quantity: 1, unit: '컵', category: 'etc', pantryStaple: false },
      { name: '레몬', quantity: 1, unit: '개', category: 'fruit', pantryStaple: false },
      { name: '간장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '미림', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진 마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '생강', quantity: 1, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '식용유', quantity: 3, unit: '컵', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-yakisoba',
    name: '야키소바 (일본식 볶음면)',
    cuisine: 'JP',
    type: 'home',
    description: '돼지고기와 채소를 면과 함께 진한 소스에 볶아낸 길거리 인기 면요리.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 560,
    tags: ['면', '볶음', '돼지고기', '간편'],
    recipe: {
      steps: [
        '1. 양배추는 큼직하게 썰고 당근과 양파는 채 썬다.',
        '2. 달군 팬에 식용유를 두르고 돼지고기를 볶는다.',
        '3. 채소를 넣고 숨이 죽을 때까지 볶는다.',
        '4. 데친 야키소바 면을 넣고 가볍게 풀어준다.',
        '5. 야키소바 소스와 굴소스를 넣고 빠르게 볶는다.',
        '6. 가쓰오부시와 김가루를 뿌려 완성한다.',
      ],
      tips: [
        '면은 살짝만 데쳐 볶아야 불지 않고 탱탱하다.',
        '소스는 면이 거의 다 볶였을 때 넣어야 타지 않는다.',
      ],
    },
    ingredients: [
      { name: '야키소바 면', quantity: 2, unit: '개', category: 'grain', pantryStaple: false },
      { name: '돼지고기 앞다리살', quantity: 150, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양배추', quantity: 150, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '야키소바 소스', quantity: 4, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '굴소스', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '가쓰오부시', quantity: 1, unit: '약간', category: 'seafood', pantryStaple: false },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-okonomiyaki',
    name: '오코노미야키',
    cuisine: 'JP',
    type: 'home',
    description: '양배추 반죽을 부쳐 소스와 마요네즈, 가쓰오부시를 올린 일본식 부침.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 540,
    tags: ['부침', '양배추', '간식'],
    recipe: {
      steps: [
        '1. 양배추는 얇게 채 썰고 쪽파는 송송 썬다.',
        '2. 볼에 밀가루, 물, 달걀을 넣고 반죽을 만든다.',
        '3. 채 썬 양배추와 쪽파를 넣고 가볍게 섞는다.',
        '4. 달군 팬에 반죽을 도톰하게 올리고 위에 삼겹살을 깐다.',
        '5. 노릇해지면 뒤집어 양면을 익힌다.',
        '6. 오코노미야키 소스와 마요네즈, 가쓰오부시, 김가루를 올린다.',
      ],
      tips: [
        '반죽은 너무 세게 젓지 말고 양배추가 으스러지지 않게 섞는다.',
        '뒤집을 때 접시를 이용하면 모양이 무너지지 않는다.',
      ],
    },
    ingredients: [
      { name: '양배추', quantity: 300, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '밀가루', quantity: 1, unit: '컵', category: 'grain', pantryStaple: true },
      { name: '달걀', quantity: 2, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '삼겹살', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '쪽파', quantity: 2, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '오코노미야키 소스', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '마요네즈', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '가쓰오부시', quantity: 1, unit: '약간', category: 'seafood', pantryStaple: false },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-miso-soup',
    name: '미소시루 (일본식 된장국)',
    cuisine: 'JP',
    type: 'home',
    description: '가다랑어 육수에 미소를 풀고 두부와 미역을 넣은 담백한 국.',
    difficulty: 'easy',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 120,
    tags: ['국물', '두부', '담백', '반찬'],
    recipe: {
      steps: [
        '1. 냄비에 물을 붓고 다시팩을 넣어 5분간 우려 육수를 낸다.',
        '2. 다시팩을 건지고 마른 미역을 불려 넣는다.',
        '3. 두부를 깍둑 썰어 넣고 약한 불로 끓인다.',
        '4. 미소를 체에 받쳐 국물에 곱게 풀어준다.',
        '5. 한소끔만 끓이고 끓어 넘기 전에 불을 끈다.',
        '6. 쪽파를 송송 썰어 올려 완성한다.',
      ],
      tips: [
        '미소를 넣은 뒤에는 팔팔 끓이지 않아야 향이 날아가지 않는다.',
        '두부는 마지막에 넣어 부서지지 않게 한다.',
      ],
    },
    ingredients: [
      { name: '미소된장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '두부', quantity: 150, unit: 'g', category: 'etc', pantryStaple: false },
      { name: '마른 미역', quantity: 5, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '다시팩', quantity: 1, unit: '개', category: 'seasoning', pantryStaple: false },
      { name: '쪽파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '물', quantity: 3, unit: '컵', category: 'etc', pantryStaple: true },
    ],
  },
  {
    id: 'jp-kake-udon',
    name: '가케우동',
    cuisine: 'JP',
    type: 'home',
    description: '맑은 가다랑어 육수에 통통한 우동면을 말아낸 따뜻한 면요리.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 430,
    tags: ['면', '국물', '따뜻한', '간편'],
    recipe: {
      steps: [
        '1. 냄비에 물과 다시팩을 넣고 5분 우려 육수를 만든다.',
        '2. 다시팩을 건지고 간장, 미림, 소금으로 간을 맞춘다.',
        '3. 다른 냄비에 우동면을 삶아 찬물에 헹군다.',
        '4. 헹군 면을 끓는 육수에 다시 데운다.',
        '5. 그릇에 면을 담고 뜨거운 육수를 붓는다.',
        '6. 쪽파, 어묵, 가쓰오부시를 올려 완성한다.',
      ],
      tips: [
        '면을 한 번 헹궈 전분기를 빼면 국물이 맑게 유지된다.',
        '유부나 튀김을 올리면 든든한 한 끼가 된다.',
      ],
    },
    ingredients: [
      { name: '우동면', quantity: 2, unit: '개', category: 'grain', pantryStaple: false },
      { name: '다시팩', quantity: 1, unit: '개', category: 'seasoning', pantryStaple: false },
      { name: '어묵', quantity: 100, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '쪽파', quantity: 2, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '미림', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '물', quantity: 4, unit: '컵', category: 'etc', pantryStaple: true },
    ],
  },
  {
    id: 'jp-chicken-teriyaki',
    name: '데리야키 치킨',
    cuisine: 'JP',
    type: 'home',
    description: '닭다리살을 노릇하게 구워 윤기나는 데리야키 소스를 입힌 요리.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 560,
    tags: ['닭고기', '구이', '달콤짭짤', '밥반찬'],
    recipe: {
      steps: [
        '1. 닭다리살의 두꺼운 부분에 칼집을 내고 소금, 후추로 밑간한다.',
        '2. 간장, 미림, 설탕, 청주를 섞어 데리야키 소스를 만든다.',
        '3. 팬에 기름을 두르고 닭을 껍질 쪽부터 노릇하게 굽는다.',
        '4. 뒤집어 속까지 익힌 뒤 기름을 닦아낸다.',
        '5. 소스를 붓고 졸이며 닭에 끼얹어 윤기를 낸다.',
        '6. 먹기 좋게 썰어 통깨를 뿌려 낸다.',
      ],
      tips: [
        '소스는 약불에서 졸여야 타지 않고 윤기가 난다.',
        '껍질을 바삭하게 구우면 식감이 살아난다.',
      ],
    },
    ingredients: [
      { name: '닭다리살', quantity: 400, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '미림', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '청주', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '통깨', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-chawanmushi',
    name: '차완무시 (일본식 달걀찜)',
    cuisine: 'JP',
    type: 'home',
    description: '육수에 달걀을 풀어 부드럽게 쪄낸 푸딩 같은 일본식 달걀찜.',
    difficulty: 'medium',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 160,
    tags: ['달걀', '찜', '담백', '반찬'],
    recipe: {
      steps: [
        '1. 따뜻한 다시 육수에 간장과 소금으로 연하게 간한다.',
        '2. 달걀을 풀고 식힌 육수와 1:3 비율로 섞는다.',
        '3. 달걀물을 체에 한 번 걸러 곱게 만든다.',
        '4. 그릇에 새우와 표고버섯을 담고 달걀물을 붓는다.',
        '5. 김이 오른 찜기에 약불로 12분간 찐다.',
        '6. 표면이 탱글하게 굳으면 쪽파를 올려 낸다.',
      ],
      tips: [
        '약불로 천천히 쪄야 기포 없이 매끈하게 완성된다.',
        '뚜껑에 면포를 받치면 물방울이 떨어지지 않는다.',
      ],
    },
    ingredients: [
      { name: '달걀', quantity: 3, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '칵테일새우', quantity: 60, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '표고버섯', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '다시팩', quantity: 1, unit: '개', category: 'seasoning', pantryStaple: false },
      { name: '쪽파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '물', quantity: 2, unit: '컵', category: 'etc', pantryStaple: true },
    ],
  },
  {
    id: 'jp-nikujaga',
    name: '니쿠자가 (일본식 소고기감자조림)',
    cuisine: 'JP',
    type: 'home',
    description: '소고기와 감자, 양파를 달콤한 간장 양념에 졸인 일본 가정식 조림.',
    difficulty: 'easy',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 480,
    tags: ['조림', '소고기', '감자', '가정식'],
    recipe: {
      steps: [
        '1. 감자와 당근은 큼직하게 썰고 양파는 굵게 썬다.',
        '2. 냄비에 기름을 두르고 소고기를 볶아 색을 낸다.',
        '3. 감자, 당근, 양파를 넣고 가볍게 볶는다.',
        '4. 물, 간장, 미림, 설탕을 넣고 끓인다.',
        '5. 뚜껑을 덮고 중약불에서 감자가 익을 때까지 졸인다.',
        '6. 국물이 자작해지면 불을 끄고 그대로 식혀 맛을 들인다.',
      ],
      tips: [
        '한 김 식히면 양념이 속까지 배어 더 맛있다.',
        '감자가 으스러지지 않게 너무 세게 젓지 않는다.',
      ],
    },
    ingredients: [
      { name: '소고기 불고기감', quantity: 200, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '감자', quantity: 3, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '미림', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-onigiri',
    name: '오니기리 (일본식 주먹밥)',
    cuisine: 'JP',
    type: 'home',
    description: '소금간한 밥에 속을 넣고 김으로 감싼 간단한 일본식 주먹밥.',
    difficulty: 'easy',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 380,
    tags: ['밥', '간편', '도시락'],
    recipe: {
      steps: [
        '1. 따뜻한 밥에 소금을 약간 넣어 고루 섞는다.',
        '2. 참치마요와 우메보시 등 속재료를 준비한다.',
        '3. 손에 물을 묻히고 소금을 살짝 바른다.',
        '4. 밥을 펴 속재료를 넣고 삼각형으로 단단히 뭉친다.',
        '5. 김을 둘러 감싼다.',
        '6. 통깨를 뿌려 마무리한다.',
      ],
      tips: [
        '손에 물과 소금을 묻히면 밥이 들러붙지 않고 간도 밴다.',
        '김은 먹기 직전에 둘러야 눅눅해지지 않는다.',
      ],
    },
    ingredients: [
      { name: '밥', quantity: 2, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '통조림 참치', quantity: 1, unit: '개', category: 'seafood', pantryStaple: false },
      { name: '마요네즈', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '구운 김', quantity: 2, unit: '장', category: 'seafood', pantryStaple: false },
      { name: '통깨', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-tamagoyaki',
    name: '다마고야키 (달걀말이)',
    cuisine: 'JP',
    type: 'home',
    description: '육수와 미림을 더한 달걀물을 여러 겹 말아낸 부드러운 달걀말이.',
    difficulty: 'medium',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 230,
    tags: ['달걀', '반찬', '도시락'],
    recipe: {
      steps: [
        '1. 달걀을 풀고 다시 육수, 미림, 소금을 넣어 곱게 섞는다.',
        '2. 달걀물을 체에 걸러 알끈을 제거한다.',
        '3. 사각팬을 약불로 달구고 기름을 얇게 두른다.',
        '4. 달걀물을 한 국자 부어 살짝 익으면 한쪽으로 말아준다.',
        '5. 빈 자리에 기름을 두르고 달걀물을 부어 다시 만다.',
        '6. 같은 방식을 반복한 뒤 김발로 모양을 잡아 썬다.',
      ],
      tips: [
        '약불에서 여러 번 얇게 부어 말아야 결이 곱다.',
        '김발로 감싸 식히면 단면 모양이 예쁘게 잡힌다.',
      ],
    },
    ingredients: [
      { name: '달걀', quantity: 4, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '다시팩', quantity: 1, unit: '개', category: 'seasoning', pantryStaple: false },
      { name: '미림', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-japanese-curry',
    name: '일본식 카레라이스',
    cuisine: 'JP',
    type: 'home',
    description: '소고기와 채소를 푹 끓여 카레 루로 진하게 농축한 일본식 카레.',
    difficulty: 'easy',
    cookTimeMin: 40,
    servings: 2,
    estimatedCalories: 720,
    tags: ['카레', '밥', '소고기', '한그릇'],
    recipe: {
      steps: [
        '1. 감자, 당근, 양파는 큼직하게 썬다.',
        '2. 냄비에 기름을 두르고 소고기를 볶아 색을 낸다.',
        '3. 양파를 넣고 갈색이 날 때까지 충분히 볶는다.',
        '4. 감자, 당근과 물을 넣고 채소가 익을 때까지 끓인다.',
        '5. 불을 줄이고 카레 루를 넣어 곱게 녹인다.',
        '6. 농도가 걸쭉해질 때까지 저으며 끓여 밥과 함께 낸다.',
      ],
      tips: [
        '양파를 갈색이 날 때까지 볶으면 단맛과 깊이가 살아난다.',
        '루를 넣은 뒤에는 약불로 저어가며 끓여야 바닥이 타지 않는다.',
      ],
    },
    ingredients: [
      { name: '소고기 카레용', quantity: 200, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '감자', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '일본식 카레 루', quantity: 100, unit: 'g', category: 'seasoning', pantryStaple: false },
      { name: '밥', quantity: 2, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '물', quantity: 3, unit: '컵', category: 'etc', pantryStaple: true },
    ],
  },
  {
    id: 'jp-shoyu-ramen',
    name: '쇼유라멘 (간장라멘)',
    cuisine: 'JP',
    type: 'home',
    description: '간장 베이스의 맑은 국물에 차슈와 반숙란을 올린 일본식 라멘.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 640,
    tags: ['면', '국물', '돼지고기', '한그릇'],
    recipe: {
      steps: [
        '1. 냄비에 물과 다시팩, 대파 뿌리를 넣고 우려 육수를 낸다.',
        '2. 간장, 미림, 굴소스로 라멘 국물의 간을 맞춘다.',
        '3. 라멘 면을 따로 삶아 건진다.',
        '4. 그릇에 면을 담고 뜨거운 국물을 붓는다.',
        '5. 차슈와 반숙란을 반으로 잘라 올린다.',
        '6. 쪽파, 김, 멘마를 올려 완성한다.',
      ],
      tips: [
        '면과 국물을 따로 준비해야 면이 붇지 않는다.',
        '반숙란은 미리 간장에 절여두면 풍미가 깊다.',
      ],
    },
    ingredients: [
      { name: '라멘 면', quantity: 2, unit: '개', category: 'grain', pantryStaple: false },
      { name: '차슈', quantity: 120, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '달걀', quantity: 2, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '구운 김', quantity: 2, unit: '장', category: 'seafood', pantryStaple: false },
      { name: '다시팩', quantity: 1, unit: '개', category: 'seasoning', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '미림', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '굴소스', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '물', quantity: 4, unit: '컵', category: 'etc', pantryStaple: true },
    ],
  },
  {
    id: 'jp-ebi-tempura',
    name: '에비텐푸라 (새우튀김)',
    cuisine: 'JP',
    type: 'home',
    description: '차가운 튀김옷을 입혀 바삭하고 가볍게 튀긴 새우 튀김.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 450,
    tags: ['튀김', '새우', '바삭'],
    recipe: {
      steps: [
        '1. 새우는 껍질과 내장을 제거하고 배 쪽에 칼집을 내 곧게 편다.',
        '2. 물기를 닦고 밀가루를 살짝 묻혀둔다.',
        '3. 찬물과 달걀, 밀가루를 가볍게 섞어 튀김옷을 만든다.',
        '4. 새우에 튀김옷을 입혀 175도 기름에 넣는다.',
        '5. 노릇하고 바삭해질 때까지 2~3분 튀긴다.',
        '6. 기름을 빼고 덴쓰유와 무즙을 곁들여 낸다.',
      ],
      tips: [
        '튀김옷은 차갑게, 살짝만 섞어야 바삭하게 튀겨진다.',
        '새우 배에 칼집을 내면 튀길 때 휘지 않고 곧게 펴진다.',
      ],
    },
    ingredients: [
      { name: '생새우', quantity: 10, unit: '개', category: 'seafood', pantryStaple: false },
      { name: '밀가루', quantity: 1, unit: '컵', category: 'grain', pantryStaple: true },
      { name: '달걀', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '무', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '덴쓰유', quantity: 4, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '식용유', quantity: 3, unit: '컵', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-tendon',
    name: '텐동 (튀김덮밥)',
    cuisine: 'JP',
    type: 'home',
    description: '바삭한 새우와 채소 튀김을 달콤한 덴쓰유에 적셔 밥에 올린 덮밥.',
    difficulty: 'medium',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 760,
    tags: ['덮밥', '튀김', '새우', '한그릇'],
    recipe: {
      steps: [
        '1. 새우와 가지, 단호박을 손질해 튀김옷을 입힌다.',
        '2. 175도 기름에 재료를 바삭하게 튀겨 건진다.',
        '3. 간장, 미림, 설탕, 물을 끓여 덴쓰유를 졸인다.',
        '4. 튀김을 덴쓰유에 살짝 담가 소스를 입힌다.',
        '5. 그릇에 밥을 담고 튀김을 보기 좋게 올린다.',
        '6. 남은 덴쓰유를 끼얹어 완성한다.',
      ],
      tips: [
        '소스는 살짝만 묻혀야 튀김의 바삭함이 유지된다.',
        '튀김은 두께가 비슷하게 썰어야 고르게 익는다.',
      ],
    },
    ingredients: [
      { name: '생새우', quantity: 6, unit: '개', category: 'seafood', pantryStaple: false },
      { name: '가지', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '단호박', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '밀가루', quantity: 1, unit: '컵', category: 'grain', pantryStaple: true },
      { name: '달걀', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '밥', quantity: 2, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '미림', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 3, unit: '컵', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-saba-shioyaki',
    name: '사바 시오야키 (고등어 소금구이)',
    cuisine: 'JP',
    type: 'home',
    description: '소금을 뿌려 노릇하게 구운 담백한 고등어 소금구이.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 380,
    tags: ['생선', '구이', '담백', '밥반찬'],
    recipe: {
      steps: [
        '1. 고등어는 물기를 닦고 양면에 칼집을 낸다.',
        '2. 소금을 골고루 뿌려 15분간 둔다.',
        '3. 배어 나온 물기를 닦아낸다.',
        '4. 달군 그릴팬에 기름을 두르고 껍질 쪽부터 굽는다.',
        '5. 노릇해지면 뒤집어 속까지 익힌다.',
        '6. 무즙과 레몬을 곁들여 낸다.',
      ],
      tips: [
        '소금을 미리 뿌려 물기를 빼면 비린내가 줄고 살이 탱탱해진다.',
        '껍질부터 구우면 모양이 흐트러지지 않는다.',
      ],
    },
    ingredients: [
      { name: '고등어', quantity: 1, unit: '개', category: 'seafood', pantryStaple: false },
      { name: '무', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '레몬', quantity: 1, unit: '개', category: 'fruit', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-gyoza',
    name: '교자 (일본식 군만두)',
    cuisine: 'JP',
    type: 'home',
    description: '돼지고기와 부추 소를 넣어 한 면을 바삭하게 구운 일본식 만두.',
    difficulty: 'medium',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 470,
    tags: ['만두', '돼지고기', '구이', '안주'],
    recipe: {
      steps: [
        '1. 다진 돼지고기에 다진 양배추, 부추, 다진 마늘을 섞는다.',
        '2. 간장, 참기름, 소금, 후추로 소를 양념한다.',
        '3. 만두피에 소를 넣고 주름을 잡아 빚는다.',
        '4. 달군 팬에 기름을 두르고 만두 바닥을 노릇하게 굽는다.',
        '5. 물을 약간 붓고 뚜껑을 덮어 증기로 익힌다.',
        '6. 물이 마르면 바닥이 바삭해지게 마저 구워 낸다.',
      ],
      tips: [
        '물을 붓고 찌듯 구우면 속은 촉촉, 바닥은 바삭해진다.',
        '간장과 식초, 라유를 섞어 소스를 만들어 곁들인다.',
      ],
    },
    ingredients: [
      { name: '다진 돼지고기', quantity: 200, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양배추', quantity: 150, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '부추', quantity: 50, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '만두피', quantity: 20, unit: '장', category: 'grain', pantryStaple: false },
      { name: '다진 마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-omurice',
    name: '오므라이스',
    cuisine: 'JP',
    type: 'home',
    description: '케첩 볶음밥을 부드러운 달걀로 감싼 일본식 경양식 메뉴.',
    difficulty: 'medium',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 640,
    tags: ['밥', '달걀', '케첩', '한그릇'],
    recipe: {
      steps: [
        '1. 양파와 닭고기, 당근을 잘게 썬다.',
        '2. 팬에 기름을 두르고 채소와 닭고기를 볶는다.',
        '3. 밥과 케첩을 넣고 고루 볶아 간한다.',
        '4. 볶음밥을 접시에 길쭉하게 담아둔다.',
        '5. 달걀을 풀어 팬에 부어 반숙 오믈렛을 만든다.',
        '6. 오믈렛으로 밥을 덮고 케첩으로 장식한다.',
      ],
      tips: [
        '달걀은 반숙 상태에서 밥 위에 덮어야 부드럽다.',
        '볶음밥을 키친타월로 감싸 모양을 잡으면 깔끔하다.',
      ],
    },
    ingredients: [
      { name: '밥', quantity: 2, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '닭다리살', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '달걀', quantity: 4, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '케첩', quantity: 4, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-zaru-soba',
    name: '자루소바 (메밀국수)',
    cuisine: 'JP',
    type: 'home',
    description: '차갑게 헹군 메밀면을 진한 쓰유에 찍어 먹는 여름철 면요리.',
    difficulty: 'easy',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 360,
    tags: ['면', '메밀', '시원한', '간편'],
    recipe: {
      steps: [
        '1. 다시 육수에 간장과 미림을 섞어 쓰유를 만들어 식힌다.',
        '2. 끓는 물에 메밀면을 삶는다.',
        '3. 삶은 면을 찬물에 비벼 헹궈 전분기를 뺀다.',
        '4. 얼음물에 한 번 더 헹궈 차갑게 식힌다.',
        '5. 물기를 빼고 채반에 면을 담는다.',
        '6. 쪽파와 와사비를 곁들여 쓰유에 찍어 먹는다.',
      ],
      tips: [
        '면을 얼음물에 헹구면 더 쫄깃하고 시원하다.',
        '쓰유는 차갑게 준비해야 면 맛이 산다.',
      ],
    },
    ingredients: [
      { name: '메밀면', quantity: 2, unit: '개', category: 'grain', pantryStaple: false },
      { name: '다시팩', quantity: 1, unit: '개', category: 'seasoning', pantryStaple: false },
      { name: '구운 김', quantity: 1, unit: '장', category: 'seafood', pantryStaple: false },
      { name: '쪽파', quantity: 2, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '와사비', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '미림', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-buta-shogayaki',
    name: '부타노 쇼가야키 (돼지고기 생강구이)',
    cuisine: 'JP',
    type: 'home',
    description: '얇은 돼지고기를 생강 간장 양념에 볶아낸 밥도둑 일본 가정식.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 540,
    tags: ['돼지고기', '볶음', '생강', '밥반찬'],
    recipe: {
      steps: [
        '1. 양파는 채 썰고 생강은 곱게 갈아 즙을 낸다.',
        '2. 간장, 미림, 청주, 생강즙을 섞어 양념을 만든다.',
        '3. 팬에 기름을 두르고 양파를 먼저 볶는다.',
        '4. 돼지고기를 넣고 펼쳐 익힌다.',
        '5. 양념을 붓고 고기에 고루 배도록 볶는다.',
        '6. 국물이 졸아들면 채 썬 양배추와 함께 낸다.',
      ],
      tips: [
        '생강즙은 마지막에 넣어야 향이 살아난다.',
        '센 불에서 빠르게 볶아야 고기가 질겨지지 않는다.',
      ],
    },
    ingredients: [
      { name: '돼지고기 앞다리살', quantity: 300, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양배추', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '생강', quantity: 1, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '미림', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '청주', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-takoyaki',
    name: '타코야키 (문어볼)',
    cuisine: 'JP',
    type: 'home',
    description: '반죽 속에 문어를 넣어 동그랗게 구운 오사카식 길거리 간식.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 420,
    tags: ['간식', '문어', '분식'],
    recipe: {
      steps: [
        '1. 밀가루, 달걀, 다시 육수를 섞어 묽은 반죽을 만든다.',
        '2. 문어는 작게 썰고 쪽파는 송송 썬다.',
        '3. 달군 타코야키 틀에 기름을 바르고 반죽을 가득 붓는다.',
        '4. 문어와 쪽파를 올리고 겉이 익으면 꼬치로 돌려준다.',
        '5. 굴려가며 동그랗게 모양을 잡아 노릇하게 굽는다.',
        '6. 타코야키 소스, 마요네즈, 가쓰오부시를 올려 낸다.',
      ],
      tips: [
        '반죽은 살짝 묽게 해야 속이 부드럽게 익는다.',
        '꼬치로 반복해서 굴려야 동그란 모양이 잡힌다.',
      ],
    },
    ingredients: [
      { name: '밀가루', quantity: 1, unit: '컵', category: 'grain', pantryStaple: true },
      { name: '달걀', quantity: 2, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '자숙문어', quantity: 120, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '쪽파', quantity: 2, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '다시팩', quantity: 1, unit: '개', category: 'seasoning', pantryStaple: false },
      { name: '타코야키 소스', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '마요네즈', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '가쓰오부시', quantity: 1, unit: '약간', category: 'seafood', pantryStaple: false },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'jp-hambagu',
    name: '함바그 (일본식 햄버그스테이크)',
    cuisine: 'JP',
    type: 'home',
    description: '다진 고기를 도톰하게 빚어 구운 뒤 데미글라스 소스를 끼얹은 함박스테이크.',
    difficulty: 'medium',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 680,
    tags: ['고기', '구이', '경양식', '소스'],
    recipe: {
      steps: [
        '1. 다진 양파를 볶아 식히고 빵가루는 우유에 불린다.',
        '2. 다진 고기에 양파, 빵가루, 달걀, 소금, 후추를 넣고 치댄다.',
        '3. 반죽을 타원형으로 빚고 가운데를 살짝 눌러준다.',
        '4. 팬에 기름을 두르고 양면을 노릇하게 굽는다.',
        '5. 물을 약간 붓고 뚜껑을 덮어 속까지 익힌다.',
        '6. 케첩과 우스터소스를 졸여 만든 소스를 끼얹어 낸다.',
      ],
      tips: [
        '반죽을 끈기가 생길 때까지 치대야 부서지지 않는다.',
        '가운데를 눌러두면 구울 때 고르게 익는다.',
      ],
    },
    ingredients: [
      { name: '다진 소고기', quantity: 200, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '다진 돼지고기', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '빵가루', quantity: 4, unit: '큰술', category: 'grain', pantryStaple: false },
      { name: '달걀', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '우유', quantity: 3, unit: '큰술', category: 'dairy', pantryStaple: false },
      { name: '케첩', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '우스터소스', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
];
