import type { SeedMenu } from '../types';

/**
 * 한식(KR) 시드 레시피 풀 — RULES R9.
 * 모든 항목은 type:"home", cuisine:"KR" 이며 안정적 슬러그 id(kr-*)를 가진다.
 * 단위/카테고리/pantryStaple은 R4 코드와 1:1.
 */
export const krSeed: SeedMenu[] = [
  {
    id: 'kr-kimchi-jjigae',
    name: '김치찌개',
    cuisine: 'KR',
    type: 'home',
    description: '잘 익은 김치와 돼지고기로 끓인 얼큰한 국물 요리.',
    difficulty: 'easy',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 420,
    tags: ['매콤', '김치', '찌개', '돼지고기'],
    recipe: {
      steps: [
        '1. 돼지고기는 한입 크기로 썰고 김치는 2cm 폭으로 썬다.',
        '2. 냄비에 식용유를 두르고 돼지고기를 중불에서 볶는다.',
        '3. 고기 겉면이 익으면 김치를 넣고 함께 볶아 감칠맛을 낸다.',
        '4. 물 3컵과 김치국물을 붓고 고춧가루, 다진마늘을 넣어 끓인다.',
        '5. 끓어오르면 두부와 대파를 넣고 중불로 10분 더 끓인다.',
        '6. 간장으로 간을 맞추고 한소끔 더 끓여 마무리한다.',
      ],
      tips: [
        '신김치를 쓰면 깊은 맛이 난다.',
        '설탕을 약간 넣으면 김치의 신맛이 부드러워진다.',
      ],
    },
    ingredients: [
      { name: '잘 익은 배추김치', quantity: 300, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '돼지고기 목살', quantity: 200, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '두부', quantity: 1, unit: '개', category: 'grain', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '고춧가루', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '국간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-doenjang-jjigae',
    name: '된장찌개',
    cuisine: 'KR',
    type: 'home',
    description: '구수한 된장에 채소와 두부를 넣어 끓인 집밥 대표 찌개.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 250,
    tags: ['구수한', '된장', '찌개', '채소'],
    recipe: {
      steps: [
        '1. 멸치와 다시마를 넣고 물 3컵을 끓여 육수를 낸다.',
        '2. 다시마와 멸치를 건지고 된장을 풀어 넣는다.',
        '3. 감자와 양파를 먼저 넣고 끓인다.',
        '4. 애호박과 두부를 넣고 중불로 끓인다.',
        '5. 다진마늘과 고춧가루를 넣어 간을 맞춘다.',
        '6. 청양고추와 대파를 넣고 한소끔 더 끓여 낸다.',
      ],
      tips: [
        '된장은 한 번에 다 넣지 말고 간을 보며 추가한다.',
        '두부는 마지막에 넣어야 부서지지 않는다.',
      ],
    },
    ingredients: [
      { name: '된장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '두부', quantity: 1, unit: '개', category: 'grain', pantryStaple: false },
      { name: '애호박', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '감자', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '청양고추', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '국물용 멸치', quantity: 10, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '다시마', quantity: 1, unit: '장', category: 'seafood', pantryStaple: false },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-sundubu-jjigae',
    name: '순두부찌개',
    cuisine: 'KR',
    type: 'home',
    description: '부드러운 순두부에 매콤한 양념을 더한 얼큰한 찌개.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 320,
    tags: ['매콤', '순두부', '찌개', '계란'],
    recipe: {
      steps: [
        '1. 냄비에 식용유와 고춧가루를 넣고 약불에서 고추기름을 낸다.',
        '2. 다진 돼지고기와 다진마늘을 넣고 볶는다.',
        '3. 물 2컵과 멸치액젓을 넣고 끓인다.',
        '4. 순두부를 큼직하게 떠 넣고 끓인다.',
        '5. 대파와 소금으로 간을 맞춘다.',
        '6. 불을 끄기 직전 계란을 깨 올려 반숙으로 익힌다.',
      ],
      tips: ['고추기름을 직접 내면 색과 풍미가 살아난다.'],
    },
    ingredients: [
      { name: '순두부', quantity: 350, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '다진 돼지고기', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '계란', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '고춧가루', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '멸치액젓', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-miyeokguk',
    name: '미역국',
    cuisine: 'KR',
    type: 'home',
    description: '소고기를 넣고 푹 끓인 부드럽고 담백한 미역국.',
    difficulty: 'easy',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 180,
    tags: ['담백', '미역', '국', '소고기'],
    recipe: {
      steps: [
        '1. 마른 미역을 물에 20분간 불린 뒤 헹궈 물기를 짠다.',
        '2. 소고기는 한입 크기로 썰어 참기름에 볶는다.',
        '3. 불린 미역을 넣고 함께 볶는다.',
        '4. 물 4컵을 붓고 국간장으로 간을 한다.',
        '5. 끓어오르면 중약불로 줄여 25분간 푹 끓인다.',
        '6. 다진마늘을 넣고 소금으로 간을 마무리한다.',
      ],
      tips: [
        '미역을 충분히 볶아야 국물이 진해진다.',
        '오래 끓일수록 미역이 부드러워진다.',
      ],
    },
    ingredients: [
      { name: '마른 미역', quantity: 20, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '소고기 양지', quantity: 150, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '국간장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-yukgaejang',
    name: '육개장',
    cuisine: 'KR',
    type: 'home',
    description: '소고기와 대파를 듬뿍 넣어 얼큰하게 끓인 보양 국.',
    difficulty: 'medium',
    cookTimeMin: 70,
    servings: 2,
    estimatedCalories: 350,
    tags: ['매콤', '소고기', '국', '보양'],
    recipe: {
      steps: [
        '1. 소고기 양지를 물에 넣고 40분간 삶아 육수를 낸다.',
        '2. 삶은 고기는 건져 결대로 찢는다.',
        '3. 대파, 숙주, 고사리를 손질해 준비한다.',
        '4. 고춧가루, 다진마늘, 참기름, 국간장으로 양념장을 만든다.',
        '5. 육수에 찢은 고기와 채소, 양념장을 넣고 끓인다.',
        '6. 중불에서 20분간 끓여 맛이 어우러지면 소금으로 간한다.',
      ],
      tips: ['대파를 듬뿍 넣어야 시원하고 칼칼한 맛이 난다.'],
    },
    ingredients: [
      { name: '소고기 양지', quantity: 250, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '대파', quantity: 3, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '숙주', quantity: 150, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '삶은 고사리', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '고춧가루', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '국간장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-galbitang',
    name: '갈비탕',
    cuisine: 'KR',
    type: 'home',
    description: '소갈비를 푹 고아 맑고 진하게 끓인 보양 탕.',
    difficulty: 'medium',
    cookTimeMin: 120,
    servings: 2,
    estimatedCalories: 480,
    tags: ['담백', '소갈비', '탕', '보양'],
    recipe: {
      steps: [
        '1. 소갈비를 찬물에 1시간 담가 핏물을 뺀다.',
        '2. 끓는 물에 갈비를 데쳐 불순물을 제거하고 헹군다.',
        '3. 깨끗한 물에 갈비, 무, 대파, 마늘을 넣고 센불로 끓인다.',
        '4. 끓어오르면 중약불로 줄여 1시간 30분간 푹 곤다.',
        '5. 무는 건져 깍둑 썰고 다시 넣어 부드럽게 익힌다.',
        '6. 국간장과 소금으로 간하고 송송 썬 대파를 올린다.',
      ],
      tips: [
        '핏물을 충분히 빼야 국물이 맑게 나온다.',
        '기름은 식혀서 걷어내면 깔끔하다.',
      ],
    },
    ingredients: [
      { name: '소갈비', quantity: 500, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '무', quantity: 200, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 2, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '마늘', quantity: 5, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '국간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-budae-jjigae',
    name: '부대찌개',
    cuisine: 'KR',
    type: 'home',
    description: '햄, 소시지, 김치를 한데 끓인 푸짐한 매콤 찌개.',
    difficulty: 'easy',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 540,
    tags: ['매콤', '햄', '찌개', '푸짐'],
    recipe: {
      steps: [
        '1. 햄과 소시지는 먹기 좋게 썰고 김치는 한입 크기로 썬다.',
        '2. 냄비에 김치, 햄, 소시지, 두부를 보기 좋게 둘러 담는다.',
        '3. 고춧가루, 다진마늘, 간장, 설탕으로 양념장을 만들어 가운데 올린다.',
        '4. 물 3컵을 부어 센불로 끓인다.',
        '5. 끓어오르면 라면사리와 대파를 넣는다.',
        '6. 면이 익으면 간을 보고 마무리한다.',
      ],
      tips: ['육수 대신 사골국물을 쓰면 더 진하다.'],
    },
    ingredients: [
      { name: '스팸', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '비엔나 소시지', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '배추김치', quantity: 150, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '두부', quantity: 1, unit: '개', category: 'grain', pantryStaple: false },
      { name: '라면사리', quantity: 1, unit: '개', category: 'grain', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '고춧가루', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-jeyuk-bokkeum',
    name: '제육볶음',
    cuisine: 'KR',
    type: 'home',
    description: '고추장 양념에 돼지고기를 매콤하게 볶아낸 밥도둑.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 600,
    tags: ['매콤', '돼지고기', '볶음', '밥도둑'],
    recipe: {
      steps: [
        '1. 돼지고기 앞다리살을 한입 크기로 썬다.',
        '2. 고추장, 고춧가루, 간장, 설탕, 다진마늘로 양념장을 만든다.',
        '3. 고기에 양념장을 버무려 20분간 재운다.',
        '4. 팬에 식용유를 두르고 양파와 대파를 볶는다.',
        '5. 재운 고기를 넣고 센불에서 볶는다.',
        '6. 고기가 익으면 참기름과 깨를 뿌려 마무리한다.',
      ],
      tips: [
        '센불에서 빠르게 볶아야 고기가 질겨지지 않는다.',
        '양념에 배즙을 넣으면 고기가 부드러워진다.',
      ],
    },
    ingredients: [
      { name: '돼지고기 앞다리살', quantity: 300, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '고추장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '고춧가루', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-ojingeo-bokkeum',
    name: '오징어볶음',
    cuisine: 'KR',
    type: 'home',
    description: '쫄깃한 오징어와 채소를 매콤한 양념에 볶은 요리.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 380,
    tags: ['매콤', '오징어', '볶음', '해산물'],
    recipe: {
      steps: [
        '1. 오징어는 손질해 칼집을 넣고 한입 크기로 썬다.',
        '2. 양파, 당근, 양배추를 채 썬다.',
        '3. 고추장, 고춧가루, 간장, 설탕, 다진마늘로 양념장을 만든다.',
        '4. 팬에 식용유를 두르고 채소를 센불에 볶는다.',
        '5. 오징어와 양념장을 넣고 빠르게 볶는다.',
        '6. 대파와 참기름을 넣고 마무리한다.',
      ],
      tips: ['오징어는 오래 볶으면 질겨지니 마지막에 넣는다.'],
    },
    ingredients: [
      { name: '오징어', quantity: 2, unit: '개', category: 'seafood', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양배추', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '고추장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '고춧가루', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-dakgalbi',
    name: '닭갈비',
    cuisine: 'KR',
    type: 'home',
    description: '닭고기와 채소를 고추장 양념에 볶은 춘천식 인기 메뉴.',
    difficulty: 'medium',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 520,
    tags: ['매콤', '닭고기', '볶음', '춘천'],
    recipe: {
      steps: [
        '1. 닭다리살을 한입 크기로 썬다.',
        '2. 고추장, 고춧가루, 간장, 설탕, 다진마늘, 카레가루로 양념장을 만든다.',
        '3. 닭고기에 양념장을 버무려 30분 재운다.',
        '4. 고구마, 양배추, 양파, 떡을 큼직하게 썬다.',
        '5. 팬에 식용유를 두르고 채소와 닭고기를 넣어 볶는다.',
        '6. 재료가 익으면 깻잎과 떡을 넣고 더 볶아 마무리한다.',
      ],
      tips: [
        '남은 양념에 밥을 볶아 먹으면 별미다.',
        '카레가루를 조금 넣으면 풍미가 좋아진다.',
      ],
    },
    ingredients: [
      { name: '닭다리살', quantity: 400, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양배추', quantity: 200, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '고구마', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '떡볶이떡', quantity: 100, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '깻잎', quantity: 5, unit: '장', category: 'vegetable', pantryStaple: false },
      { name: '고추장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '고춧가루', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-japchae',
    name: '잡채',
    cuisine: 'KR',
    type: 'home',
    description: '당면과 갖은 채소를 간장 양념에 볶아낸 잔칫상 단골.',
    difficulty: 'medium',
    cookTimeMin: 45,
    servings: 2,
    estimatedCalories: 420,
    tags: ['달콤', '당면', '볶음', '채소'],
    recipe: {
      steps: [
        '1. 당면을 찬물에 30분 불린 뒤 끓는 물에 삶아 헹군다.',
        '2. 소고기는 채 썰어 간장 양념에 재운다.',
        '3. 시금치는 데치고 당근, 양파, 버섯은 채 썬다.',
        '4. 각 재료를 따로따로 볶아 둔다.',
        '5. 삶은 당면을 간장, 설탕, 참기름으로 볶아 밑간한다.',
        '6. 모든 재료를 한데 넣고 버무린 뒤 깨를 뿌린다.',
      ],
      tips: [
        '재료를 따로 볶아야 색과 식감이 살아난다.',
        '당면은 미리 밑간하면 더 맛있다.',
      ],
    },
    ingredients: [
      { name: '당면', quantity: 150, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '소고기 채끝', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '시금치', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '표고버섯', quantity: 3, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '깨', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-bulgogi',
    name: '소불고기',
    cuisine: 'KR',
    type: 'home',
    description: '얇게 썬 소고기를 달콤짭짤한 간장 양념에 재워 볶은 요리.',
    difficulty: 'easy',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 450,
    tags: ['달콤', '소고기', '볶음', '간장'],
    recipe: {
      steps: [
        '1. 불고기용 소고기는 키친타월로 핏물을 닦는다.',
        '2. 간장, 설탕, 다진마늘, 참기름, 후추, 배즙으로 양념장을 만든다.',
        '3. 고기에 양념장을 버무려 30분 재운다.',
        '4. 양파와 당근, 대파를 채 썬다.',
        '5. 달군 팬에 고기와 채소를 넣고 센불에 볶는다.',
        '6. 국물이 자작해지면 깨를 뿌려 마무리한다.',
      ],
      tips: ['배즙이나 키위즙을 넣으면 고기가 연해진다.'],
    },
    ingredients: [
      { name: '불고기용 소고기', quantity: 300, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-godeungeo-gui',
    name: '고등어구이',
    cuisine: 'KR',
    type: 'home',
    description: '소금간한 고등어를 노릇하게 구워낸 담백한 생선구이.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 320,
    tags: ['담백', '고등어', '구이', '생선'],
    recipe: {
      steps: [
        '1. 손질된 고등어를 흐르는 물에 헹궈 물기를 닦는다.',
        '2. 양면에 소금을 뿌려 15분간 둔다.',
        '3. 키친타월로 표면 물기를 다시 닦는다.',
        '4. 팬이나 그릴에 식용유를 두르고 껍질 쪽부터 굽는다.',
        '5. 노릇해지면 뒤집어 속까지 익힌다.',
        '6. 레몬을 곁들여 낸다.',
      ],
      tips: [
        '굽기 전 물기를 잘 제거해야 비린내가 덜하다.',
        '껍질 쪽부터 구워야 모양이 예쁘다.',
      ],
    },
    ingredients: [
      { name: '고등어', quantity: 1, unit: '개', category: 'seafood', pantryStaple: false },
      { name: '레몬', quantity: 1, unit: '개', category: 'fruit', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-samgyeopsal',
    name: '삼겹살구이',
    cuisine: 'KR',
    type: 'home',
    description: '두툼한 삼겹살을 바삭하게 구워 쌈과 함께 먹는 한상.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 700,
    tags: ['고소', '돼지고기', '구이', '쌈'],
    recipe: {
      steps: [
        '1. 삼겹살은 실온에 잠시 두었다가 굽기 좋게 썬다.',
        '2. 팬이나 불판을 충분히 달군다.',
        '3. 삼겹살을 올려 한 면이 노릇해질 때까지 굽는다.',
        '4. 뒤집어 반대 면도 바삭하게 굽는다.',
        '5. 마늘과 김치를 함께 구워 곁들인다.',
        '6. 상추와 쌈장을 곁들여 쌈으로 낸다.',
      ],
      tips: ['고기를 자주 뒤집지 말고 한 면씩 충분히 구워야 육즙이 산다.'],
    },
    ingredients: [
      { name: '삼겹살', quantity: 400, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '상추', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '마늘', quantity: 6, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '배추김치', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '쌈장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-gyeranmari',
    name: '계란말이',
    cuisine: 'KR',
    type: 'home',
    description: '풀어둔 계란에 채소를 넣고 도톰하게 말아낸 반찬.',
    difficulty: 'easy',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 220,
    tags: ['담백', '계란', '반찬', '간단'],
    recipe: {
      steps: [
        '1. 계란을 풀고 소금으로 간한다.',
        '2. 당근, 대파, 양파를 잘게 다져 넣고 섞는다.',
        '3. 팬에 식용유를 얇게 두르고 약불로 달군다.',
        '4. 계란물을 부어 반쯤 익으면 한쪽부터 말아준다.',
        '5. 빈 자리에 계란물을 더 부어 이어 말기를 반복한다.',
        '6. 한 김 식힌 뒤 먹기 좋게 썬다.',
      ],
      tips: [
        '약불에서 천천히 말아야 모양이 곱다.',
        '계란물을 체에 한번 거르면 더 부드럽다.',
      ],
    },
    ingredients: [
      { name: '계란', quantity: 4, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-galbijjim',
    name: '갈비찜',
    cuisine: 'KR',
    type: 'home',
    description: '소갈비를 간장 양념에 푹 졸여 부드럽게 익힌 잔치 음식.',
    difficulty: 'hard',
    cookTimeMin: 90,
    servings: 2,
    estimatedCalories: 620,
    tags: ['달콤', '소갈비', '조림', '잔치'],
    recipe: {
      steps: [
        '1. 소갈비를 찬물에 1시간 담가 핏물을 뺀다.',
        '2. 끓는 물에 데쳐 불순물을 제거하고 칼집을 넣는다.',
        '3. 간장, 설탕, 다진마늘, 배즙, 참기름으로 양념장을 만든다.',
        '4. 냄비에 갈비와 양념장, 물을 넣고 센불로 끓인다.',
        '5. 끓어오르면 중약불로 줄여 50분간 졸인다.',
        '6. 무, 당근, 밤, 대추를 넣고 국물이 자작해질 때까지 익힌다.',
      ],
      tips: [
        '핏물 제거와 데치기를 거쳐야 잡내가 없다.',
        '한 김 식혔다 다시 데우면 양념이 더 밴다.',
      ],
    },
    ingredients: [
      { name: '소갈비', quantity: 500, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '무', quantity: 150, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '밤', quantity: 6, unit: '개', category: 'etc', pantryStaple: false },
      { name: '대추', quantity: 4, unit: '개', category: 'fruit', pantryStaple: false },
      { name: '간장', quantity: 5, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-dakbokkeumtang',
    name: '닭볶음탕',
    cuisine: 'KR',
    type: 'home',
    description: '닭과 감자를 고춧가루 양념에 매콤하게 졸인 한 그릇.',
    difficulty: 'medium',
    cookTimeMin: 45,
    servings: 2,
    estimatedCalories: 560,
    tags: ['매콤', '닭고기', '조림', '감자'],
    recipe: {
      steps: [
        '1. 닭을 끓는 물에 데쳐 기름기와 불순물을 제거한다.',
        '2. 감자, 당근, 양파를 큼직하게 썬다.',
        '3. 고춧가루, 고추장, 간장, 설탕, 다진마늘로 양념장을 만든다.',
        '4. 냄비에 닭과 양념장, 물을 넣고 끓인다.',
        '5. 끓으면 감자와 당근을 넣고 중불로 졸인다.',
        '6. 국물이 자작해지면 양파와 대파를 넣고 마무리한다.',
      ],
      tips: ['감자가 양념을 머금어야 맛있으니 푹 익힌다.'],
    },
    ingredients: [
      { name: '닭 볶음용', quantity: 600, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '감자', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '고춧가루', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '고추장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-godeungeo-jorim',
    name: '고등어조림',
    cuisine: 'KR',
    type: 'home',
    description: '무와 고등어를 매콤한 양념에 자작하게 졸인 밥반찬.',
    difficulty: 'medium',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 360,
    tags: ['매콤', '고등어', '조림', '무'],
    recipe: {
      steps: [
        '1. 무를 도톰하게 썰어 냄비 바닥에 깐다.',
        '2. 손질한 고등어를 무 위에 올린다.',
        '3. 고춧가루, 간장, 설탕, 다진마늘, 생강으로 양념장을 만든다.',
        '4. 양념장을 끼얹고 물을 부어 센불로 끓인다.',
        '5. 끓으면 중불로 줄여 국물을 끼얹어 가며 졸인다.',
        '6. 무가 익고 국물이 자작해지면 대파를 올려 마무리한다.',
      ],
      tips: ['무를 바닥에 깔아야 생선이 눌어붙지 않는다.'],
    },
    ingredients: [
      { name: '고등어', quantity: 1, unit: '개', category: 'seafood', pantryStaple: false },
      { name: '무', quantity: 200, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '청양고추', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '고춧가루', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '생강', quantity: 1, unit: '쪽', category: 'vegetable', pantryStaple: false },
    ],
  },
  {
    id: 'kr-jangjorim',
    name: '장조림',
    cuisine: 'KR',
    type: 'home',
    description: '소고기를 간장에 짭조름하게 졸여 결대로 찢어 먹는 반찬.',
    difficulty: 'easy',
    cookTimeMin: 50,
    servings: 2,
    estimatedCalories: 240,
    tags: ['짭짤', '소고기', '조림', '밑반찬'],
    recipe: {
      steps: [
        '1. 소고기 홍두깨살을 끓는 물에 삶아 핏물을 뺀다.',
        '2. 물을 갈아 마늘, 양파와 함께 30분 더 삶는다.',
        '3. 고기를 건져 결대로 찢는다.',
        '4. 삶은 육수에 간장, 설탕, 고기를 넣고 졸인다.',
        '5. 메추리알과 꽈리고추를 넣고 함께 졸인다.',
        '6. 국물이 자작해지면 불을 끄고 식힌다.',
      ],
      tips: ['식으면서 간이 배니 너무 짜지 않게 졸인다.'],
    },
    ingredients: [
      { name: '소고기 홍두깨살', quantity: 300, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '메추리알', quantity: 15, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '꽈리고추', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '마늘', quantity: 5, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 5, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-dubu-jorim',
    name: '두부조림',
    cuisine: 'KR',
    type: 'home',
    description: '노릇하게 구운 두부에 매콤 간장 양념을 끼얹어 졸인 반찬.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 230,
    tags: ['매콤', '두부', '조림', '밑반찬'],
    recipe: {
      steps: [
        '1. 두부를 1cm 두께로 썰어 소금을 뿌려 둔다.',
        '2. 키친타월로 물기를 닦고 팬에 노릇하게 굽는다.',
        '3. 간장, 고춧가루, 설탕, 다진마늘, 대파로 양념장을 만든다.',
        '4. 구운 두부를 냄비에 담고 양념장을 끼얹는다.',
        '5. 물 반 컵을 붓고 약불로 졸인다.',
        '6. 국물이 자작해지면 참기름과 깨를 뿌려 마무리한다.',
      ],
      tips: ['두부를 미리 구워야 양념을 졸여도 부서지지 않는다.'],
    },
    ingredients: [
      { name: '두부', quantity: 1, unit: '개', category: 'grain', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '간장', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '고춧가루', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-kongnamul-muchim',
    name: '콩나물무침',
    cuisine: 'KR',
    type: 'home',
    description: '아삭한 콩나물을 데쳐 참기름에 조물조물 무친 밑반찬.',
    difficulty: 'easy',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 90,
    tags: ['담백', '콩나물', '무침', '밑반찬'],
    recipe: {
      steps: [
        '1. 콩나물을 깨끗이 씻어 다듬는다.',
        '2. 끓는 물에 소금을 넣고 콩나물을 3분간 데친다.',
        '3. 찬물에 헹궈 물기를 꼭 짠다.',
        '4. 다진마늘, 소금, 참기름, 깨를 넣는다.',
        '5. 대파와 고춧가루를 넣고 조물조물 무친다.',
        '6. 간을 보고 그릇에 담아낸다.',
      ],
      tips: ['데칠 때 뚜껑을 덮거나 끝까지 열어두어야 비린내가 안 난다.'],
    },
    ingredients: [
      { name: '콩나물', quantity: 200, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '고춧가루', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '깨', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-sigeumchi-namul',
    name: '시금치나물',
    cuisine: 'KR',
    type: 'home',
    description: '데친 시금치를 참기름과 마늘에 무친 고소한 나물 반찬.',
    difficulty: 'easy',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 80,
    tags: ['고소', '시금치', '무침', '나물'],
    recipe: {
      steps: [
        '1. 시금치를 다듬어 깨끗이 씻는다.',
        '2. 끓는 물에 소금을 넣고 30초간 데친다.',
        '3. 찬물에 헹궈 물기를 짠다.',
        '4. 국간장, 다진마늘, 참기름을 넣는다.',
        '5. 깨를 뿌려 살살 무친다.',
        '6. 간을 보고 그릇에 담아낸다.',
      ],
      tips: ['오래 데치면 색이 누레지니 살짝만 데친다.'],
    },
    ingredients: [
      { name: '시금치', quantity: 200, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '국간장', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '깨', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-oi-muchim',
    name: '오이무침',
    cuisine: 'KR',
    type: 'home',
    description: '아삭한 오이를 새콤달콤 매콤하게 무친 입맛 돋우는 반찬.',
    difficulty: 'easy',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 70,
    tags: ['새콤', '오이', '무침', '여름'],
    recipe: {
      steps: [
        '1. 오이를 깨끗이 씻어 어슷하게 썬다.',
        '2. 소금에 10분간 절였다가 물기를 짠다.',
        '3. 고춧가루, 식초, 설탕, 다진마늘을 넣는다.',
        '4. 양파를 채 썰어 함께 넣는다.',
        '5. 조물조물 무쳐 간이 배게 한다.',
        '6. 참기름과 깨를 뿌려 마무리한다.',
      ],
      tips: ['살짝 절였다 무치면 아삭함이 오래간다.'],
    },
    ingredients: [
      { name: '오이', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '고춧가루', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식초', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-bibimbap',
    name: '비빔밥',
    cuisine: 'KR',
    type: 'home',
    description: '갖은 나물과 고추장을 밥에 올려 비벼 먹는 한 그릇 요리.',
    difficulty: 'medium',
    cookTimeMin: 40,
    servings: 2,
    estimatedCalories: 560,
    tags: ['매콤', '나물', '비빔', '한그릇'],
    recipe: {
      steps: [
        '1. 시금치, 콩나물, 고사리를 각각 데쳐 무친다.',
        '2. 당근과 애호박은 채 썰어 볶는다.',
        '3. 소고기는 다져 간장 양념에 볶는다.',
        '4. 그릇에 밥을 담고 준비한 나물과 고기를 색 맞춰 올린다.',
        '5. 계란프라이를 가운데 올린다.',
        '6. 고추장과 참기름을 곁들여 비벼 먹는다.',
      ],
      tips: [
        '나물은 미리 만들어 두면 차리기 편하다.',
        '돌솥에 담아 누룽지를 만들면 더 별미다.',
      ],
    },
    ingredients: [
      { name: '밥', quantity: 2, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '소고기 다짐육', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '시금치', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '콩나물', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '애호박', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '계란', quantity: 2, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '고추장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '참기름', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-kimchi-bokkeumbap',
    name: '김치볶음밥',
    cuisine: 'KR',
    type: 'home',
    description: '잘 익은 김치와 밥을 함께 볶아 계란을 올린 한 그릇.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 480,
    tags: ['매콤', '김치', '볶음밥', '간단'],
    recipe: {
      steps: [
        '1. 김치를 잘게 썰고 대파는 송송 썬다.',
        '2. 팬에 식용유를 두르고 대파를 볶아 파기름을 낸다.',
        '3. 김치를 넣고 볶다가 고춧가루와 설탕을 넣는다.',
        '4. 밥을 넣고 김치와 고루 섞어 볶는다.',
        '5. 간장으로 간하고 참기름을 두른다.',
        '6. 계란프라이를 올리고 김가루를 뿌려 낸다.',
      ],
      tips: ['신김치를 쓰고 설탕을 약간 넣으면 맛이 균형 잡힌다.'],
    },
    ingredients: [
      { name: '밥', quantity: 2, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '배추김치', quantity: 200, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '계란', quantity: 2, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '김가루', quantity: 2, unit: '큰술', category: 'seafood', pantryStaple: false },
      { name: '고춧가루', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-janchi-guksu',
    name: '잔치국수',
    cuisine: 'KR',
    type: 'home',
    description: '멸치 육수에 소면을 말고 고명을 올린 따뜻한 국수.',
    difficulty: 'easy',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 420,
    tags: ['담백', '소면', '면', '멸치육수'],
    recipe: {
      steps: [
        '1. 멸치와 다시마를 넣고 물 5컵으로 육수를 낸다.',
        '2. 육수에 국간장과 소금으로 간을 한다.',
        '3. 애호박과 당근을 채 썰어 볶아 고명을 만든다.',
        '4. 계란지단을 부쳐 채 썬다.',
        '5. 소면을 삶아 찬물에 헹군다.',
        '6. 그릇에 면을 담고 육수를 부은 뒤 고명을 올린다.',
      ],
      tips: ['면은 따로 삶아 헹궈야 국물이 탁해지지 않는다.'],
    },
    ingredients: [
      { name: '소면', quantity: 200, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '국물용 멸치', quantity: 15, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '다시마', quantity: 1, unit: '장', category: 'seafood', pantryStaple: false },
      { name: '애호박', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '계란', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '국간장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-bibim-guksu',
    name: '비빔국수',
    cuisine: 'KR',
    type: 'home',
    description: '소면을 새콤달콤 매콤한 양념에 비벼낸 시원한 국수.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 450,
    tags: ['새콤', '소면', '면', '매콤'],
    recipe: {
      steps: [
        '1. 고추장, 고춧가루, 식초, 설탕, 간장, 다진마늘로 양념장을 만든다.',
        '2. 오이와 당근을 채 썬다.',
        '3. 소면을 삶아 찬물에 여러 번 헹군다.',
        '4. 면의 물기를 빼고 양념장에 비빈다.',
        '5. 채소와 삶은 계란을 올린다.',
        '6. 참기름과 깨를 뿌려 마무리한다.',
      ],
      tips: ['면을 찬물에 충분히 헹궈야 쫄깃하다.'],
    },
    ingredients: [
      { name: '소면', quantity: 200, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '오이', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '계란', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '고추장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '고춧가루', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식초', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '간장', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '참기름', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-kalguksu',
    name: '칼국수',
    cuisine: 'KR',
    type: 'home',
    description: '멸치 육수에 쫄깃한 칼국수면과 애호박을 넣어 끓인 면 요리.',
    difficulty: 'medium',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 470,
    tags: ['담백', '칼국수', '면', '멸치육수'],
    recipe: {
      steps: [
        '1. 멸치와 다시마로 진한 육수를 낸다.',
        '2. 애호박, 양파, 감자를 채 썬다.',
        '3. 육수에 감자를 먼저 넣고 끓인다.',
        '4. 칼국수면을 넣고 서로 붙지 않게 저으며 끓인다.',
        '5. 애호박과 양파를 넣고 국간장으로 간한다.',
        '6. 대파와 다진마늘을 넣고 한소끔 더 끓여 낸다.',
      ],
      tips: [
        '면의 전분을 한번 헹구면 국물이 덜 텁텁하다.',
        '바지락을 넣으면 국물이 더 시원하다.',
      ],
    },
    ingredients: [
      { name: '칼국수면', quantity: 300, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '국물용 멸치', quantity: 15, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '다시마', quantity: 1, unit: '장', category: 'seafood', pantryStaple: false },
      { name: '애호박', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '감자', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '국간장', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '다진마늘', quantity: 1, unit: '작은술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-kimchi-jeon',
    name: '김치전',
    cuisine: 'KR',
    type: 'home',
    description: '잘 익은 김치를 반죽에 섞어 바삭하게 부친 전.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 360,
    tags: ['매콤', '김치', '전', '바삭'],
    recipe: {
      steps: [
        '1. 김치를 잘게 썰고 대파를 송송 썬다.',
        '2. 부침가루와 물을 넣어 반죽을 만든다.',
        '3. 김치와 김치국물, 대파를 넣고 섞는다.',
        '4. 팬에 식용유를 넉넉히 두르고 달군다.',
        '5. 반죽을 얇게 펴 올려 노릇하게 부친다.',
        '6. 뒤집어 양면을 바삭하게 익혀 낸다.',
      ],
      tips: [
        '김치국물을 넣으면 색과 감칠맛이 살아난다.',
        '기름을 넉넉히 둘러야 바삭하다.',
      ],
    },
    ingredients: [
      { name: '배추김치', quantity: 200, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '부침가루', quantity: 1, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '대파', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '물', quantity: 150, unit: 'ml', category: 'etc', pantryStaple: false },
      { name: '식용유', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'kr-haemul-pajeon',
    name: '해물파전',
    cuisine: 'KR',
    type: 'home',
    description: '쪽파와 해물을 듬뿍 넣어 부친 든든한 부침개.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 410,
    tags: ['고소', '해물', '전', '쪽파'],
    recipe: {
      steps: [
        '1. 쪽파를 손질해 팬 길이에 맞춰 자른다.',
        '2. 오징어와 새우를 잘게 썰어 준비한다.',
        '3. 부침가루와 물, 계란을 섞어 반죽을 만든다.',
        '4. 팬에 기름을 두르고 쪽파를 가지런히 깐다.',
        '5. 반죽을 붓고 해물을 올려 노릇하게 부친다.',
        '6. 뒤집어 양면을 바삭하게 익혀 낸다.',
      ],
      tips: ['반죽을 너무 두껍게 하지 말고 얇게 펴야 바삭하다.'],
    },
    ingredients: [
      { name: '쪽파', quantity: 150, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '오징어', quantity: 1, unit: '개', category: 'seafood', pantryStaple: false },
      { name: '새우살', quantity: 100, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '부침가루', quantity: 1, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '계란', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '물', quantity: 150, unit: 'ml', category: 'etc', pantryStaple: false },
      { name: '식용유', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
];
