import type { SeedMenu } from '../types';

/**
 * 양식(WS) 시드 레시피 풀 — RULES R9.
 * 모든 항목은 집밥(type:"home")이며 R2 스키마를 그대로 따른다.
 * id는 안정적 슬러그(prefix `ws-`)로 풀 전체에서 유일하다.
 * 단위/카테고리/pantryStaple은 R4 코드와 1:1.
 */
export const wsSeed: SeedMenu[] = [
  {
    id: 'ws-tomato-pasta',
    name: '토마토 파스타',
    cuisine: 'WS',
    type: 'home',
    description: '진한 토마토 소스에 면을 버무린 기본 파스타.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 560,
    tags: ['파스타', '토마토', '면'],
    recipe: {
      steps: [
        '1. 끓는 물에 소금을 넣고 스파게티를 8~9분간 삶는다.',
        '2. 팬에 올리브유를 두르고 다진 마늘과 양파를 볶아 향을 낸다.',
        '3. 토마토 소스를 붓고 약불에서 5분간 졸인다.',
        '4. 삶은 면과 면수 약간을 넣어 소스와 버무린다.',
        '5. 소금과 후추로 간을 맞추고 바질을 올려 마무리한다.',
      ],
      tips: [
        '면수를 조금 넣으면 소스가 면에 잘 엉겨붙는다.',
        '면은 살짝 덜 익힌 알덴테로 삶아야 식감이 좋다.',
      ],
    },
    ingredients: [
      { name: '스파게티 면', quantity: 200, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '토마토 소스', quantity: 300, unit: 'g', category: 'seasoning', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '마늘', quantity: 3, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '바질', quantity: 1, unit: '약간', category: 'vegetable', pantryStaple: false },
      { name: '올리브유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-cream-pasta',
    name: '크림 파스타',
    cuisine: 'WS',
    type: 'home',
    description: '부드러운 생크림 소스가 매력적인 크림 파스타.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 700,
    tags: ['파스타', '크림', '베이컨'],
    recipe: {
      steps: [
        '1. 스파게티를 소금 넣은 물에 8분간 삶는다.',
        '2. 팬에 버터를 녹이고 베이컨과 양파를 볶는다.',
        '3. 생크림과 우유를 붓고 약불에서 데운다.',
        '4. 파르메산 치즈를 넣어 소스를 걸쭉하게 만든다.',
        '5. 삶은 면을 넣어 버무리고 소금, 후추로 간한다.',
      ],
      tips: [
        '크림은 끓이지 말고 약불에서 데우듯 익혀야 분리되지 않는다.',
        '면수를 약간 넣어 농도를 조절한다.',
      ],
    },
    ingredients: [
      { name: '스파게티 면', quantity: 200, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '생크림', quantity: 200, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '우유', quantity: 100, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '베이컨', quantity: 80, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '파르메산 치즈', quantity: 30, unit: 'g', category: 'dairy', pantryStaple: false },
      { name: '버터', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-aglio-olio',
    name: '알리오 올리오',
    cuisine: 'WS',
    type: 'home',
    description: '마늘과 올리브유만으로 완성하는 담백한 파스타.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 520,
    tags: ['파스타', '마늘', '담백'],
    recipe: {
      steps: [
        '1. 스파게티를 소금 넣은 물에 8분간 삶는다.',
        '2. 팬에 넉넉한 올리브유를 두르고 편 썬 마늘을 약불에 볶는다.',
        '3. 페페론치노를 넣어 매운 향을 낸다.',
        '4. 삶은 면과 면수 한 국자를 넣어 빠르게 섞는다.',
        '5. 소금으로 간하고 파슬리를 뿌려 마무리한다.',
      ],
      tips: [
        '마늘은 약불에서 천천히 익혀야 쓴맛이 나지 않는다.',
        '면수의 전분이 기름과 면을 유화시켜 소스 역할을 한다.',
      ],
    },
    ingredients: [
      { name: '스파게티 면', quantity: 200, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '마늘', quantity: 6, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '페페론치노', quantity: 3, unit: '개', category: 'seasoning', pantryStaple: false },
      { name: '파슬리', quantity: 1, unit: '약간', category: 'vegetable', pantryStaple: false },
      { name: '올리브유', quantity: 4, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-beef-steak',
    name: '소고기 스테이크',
    cuisine: 'WS',
    type: 'home',
    description: '겉은 바삭 속은 촉촉하게 구운 등심 스테이크.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 750,
    tags: ['스테이크', '소고기', '구이'],
    recipe: {
      steps: [
        '1. 등심을 실온에 30분 두고 소금, 후추로 밑간한다.',
        '2. 달군 팬에 식용유를 두르고 센 불에서 한 면을 2분씩 굽는다.',
        '3. 버터, 으깬 마늘, 로즈마리를 넣고 향을 입히며 끼얹는다.',
        '4. 원하는 굽기까지 익힌 뒤 꺼내 5분간 레스팅한다.',
        '5. 결 반대로 썰어 접시에 담아낸다.',
      ],
      tips: [
        '레스팅을 거쳐야 육즙이 빠지지 않는다.',
        '고기를 굽기 전 표면 물기를 제거하면 시어링이 잘 된다.',
      ],
    },
    ingredients: [
      { name: '소고기 등심', quantity: 400, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '마늘', quantity: 4, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '로즈마리', quantity: 1, unit: '약간', category: 'vegetable', pantryStaple: false },
      { name: '버터', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-hamburg-steak',
    name: '함박 스테이크',
    cuisine: 'WS',
    type: 'home',
    description: '다진 고기를 빚어 구운 부드러운 함박 스테이크.',
    difficulty: 'medium',
    cookTimeMin: 40,
    servings: 2,
    estimatedCalories: 680,
    tags: ['함박스테이크', '다짐육', '소스'],
    recipe: {
      steps: [
        '1. 다진 양파를 볶아 식혀 둔다.',
        '2. 다진 소고기, 돼지고기에 빵가루, 우유, 달걀, 볶은 양파를 넣고 치댄다.',
        '3. 소금, 후추로 간하고 타원형으로 빚는다.',
        '4. 팬에 구워 겉면을 익힌 뒤 뚜껑을 덮어 속까지 익힌다.',
        '5. 케첩과 우스터소스를 졸여 만든 소스를 끼얹는다.',
      ],
      tips: [
        '반죽을 충분히 치대야 갈라지지 않고 쫄깃하다.',
        '가운데를 살짝 눌러 빚으면 고르게 익는다.',
      ],
    },
    ingredients: [
      { name: '다진 소고기', quantity: 200, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '다진 돼지고기', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '빵가루', quantity: 4, unit: '큰술', category: 'grain', pantryStaple: false },
      { name: '달걀', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '우유', quantity: 3, unit: '큰술', category: 'dairy', pantryStaple: false },
      { name: '케첩', quantity: 3, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '우스터소스', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-mushroom-risotto',
    name: '버섯 리조또',
    cuisine: 'WS',
    type: 'home',
    description: '버섯 향이 가득 밴 크리미한 이탈리아식 리조또.',
    difficulty: 'medium',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 590,
    tags: ['리조또', '버섯', '치즈'],
    recipe: {
      steps: [
        '1. 양파와 양송이버섯을 잘게 다지고 버섯은 한 줌 슬라이스해 둔다.',
        '2. 팬에 버터를 녹여 양파를 볶고 쌀을 넣어 투명해질 때까지 볶는다.',
        '3. 따뜻한 채수를 한 국자씩 부어가며 저어 쌀을 익힌다.',
        '4. 버섯을 넣고 쌀이 알덴테가 될 때까지 끓인다.',
        '5. 파르메산 치즈와 버터를 넣어 크리미하게 마무리한다.',
      ],
      tips: [
        '육수는 따뜻한 상태로 조금씩 부어야 쌀이 고르게 익는다.',
        '계속 저어주면 전분이 나와 크리미해진다.',
      ],
    },
    ingredients: [
      { name: '쌀', quantity: 1, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '양송이버섯', quantity: 150, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '채소 육수', quantity: 600, unit: 'ml', category: 'seasoning', pantryStaple: false },
      { name: '파르메산 치즈', quantity: 40, unit: 'g', category: 'dairy', pantryStaple: false },
      { name: '버터', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-potato-gratin',
    name: '감자 그라탕',
    cuisine: 'WS',
    type: 'home',
    description: '크림과 치즈를 올려 오븐에 구운 감자 그라탕.',
    difficulty: 'medium',
    cookTimeMin: 50,
    servings: 2,
    estimatedCalories: 620,
    tags: ['그라탕', '감자', '오븐'],
    recipe: {
      steps: [
        '1. 감자를 얇게 슬라이스하고 양파는 채 썬다.',
        '2. 냄비에 생크림, 우유, 다진 마늘, 소금을 넣고 데운다.',
        '3. 내열 그릇에 감자와 양파를 켜켜이 담고 크림을 붓는다.',
        '4. 모차렐라 치즈를 듬뿍 올린다.',
        '5. 200도 오븐에서 30분간 노릇하게 굽는다.',
      ],
      tips: [
        '감자를 최대한 얇게 썰어야 속까지 잘 익는다.',
        '윗면이 타면 호일을 덮어 마저 익힌다.',
      ],
    },
    ingredients: [
      { name: '감자', quantity: 3, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '생크림', quantity: 200, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '우유', quantity: 100, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '모차렐라 치즈', quantity: 100, unit: 'g', category: 'dairy', pantryStaple: false },
      { name: '마늘', quantity: 2, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-plain-omelette',
    name: '플레인 오믈렛',
    cuisine: 'WS',
    type: 'home',
    description: '부드럽게 말아낸 기본 프렌치 오믈렛.',
    difficulty: 'easy',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 320,
    tags: ['오믈렛', '달걀', '아침'],
    recipe: {
      steps: [
        '1. 달걀을 풀고 우유, 소금, 후추를 넣어 곱게 섞는다.',
        '2. 팬에 버터를 녹이고 약불로 달걀물을 붓는다.',
        '3. 젓가락으로 저으며 반숙 상태로 만든다.',
        '4. 한쪽부터 접어 타원형으로 말아낸다.',
        '5. 접시에 담고 파슬리를 뿌린다.',
      ],
      tips: [
        '약불에서 빠르게 저어야 부드러운 식감이 난다.',
        '달걀물을 체에 한번 거르면 더 매끄럽다.',
      ],
    },
    ingredients: [
      { name: '달걀', quantity: 4, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '우유', quantity: 2, unit: '큰술', category: 'dairy', pantryStaple: false },
      { name: '파슬리', quantity: 1, unit: '약간', category: 'vegetable', pantryStaple: false },
      { name: '버터', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-cobb-salad',
    name: '콥 샐러드',
    cuisine: 'WS',
    type: 'home',
    description: '닭가슴살과 달걀, 채소를 푸짐하게 담은 한 끼 샐러드.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 430,
    tags: ['샐러드', '닭가슴살', '건강식'],
    recipe: {
      steps: [
        '1. 닭가슴살을 삶거나 구워 한입 크기로 썬다.',
        '2. 달걀은 완숙으로 삶아 반으로 자른다.',
        '3. 로메인, 방울토마토, 아보카도를 먹기 좋게 썬다.',
        '4. 접시에 재료를 색깔별로 줄지어 담는다.',
        '5. 올리브유, 발사믹, 소금, 후추로 만든 드레싱을 뿌린다.',
      ],
      tips: [
        '아보카도는 먹기 직전에 썰어야 갈변을 막는다.',
        '닭가슴살은 결대로 찢으면 드레싱이 잘 밴다.',
      ],
    },
    ingredients: [
      { name: '닭가슴살', quantity: 200, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '로메인 상추', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '방울토마토', quantity: 8, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '아보카도', quantity: 1, unit: '개', category: 'fruit', pantryStaple: false },
      { name: '달걀', quantity: 2, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '발사믹 식초', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '올리브유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-mushroom-soup',
    name: '양송이 수프',
    cuisine: 'WS',
    type: 'home',
    description: '버섯을 곱게 갈아 끓인 부드러운 크림 수프.',
    difficulty: 'easy',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 360,
    tags: ['수프', '버섯', '크림'],
    recipe: {
      steps: [
        '1. 양송이버섯과 양파를 슬라이스한다.',
        '2. 버터에 양파와 버섯을 충분히 볶는다.',
        '3. 밀가루를 넣어 한 번 더 볶아 루를 만든다.',
        '4. 우유와 생크림을 부어 끓이며 핸드블렌더로 곱게 간다.',
        '5. 소금, 후추로 간하고 그릇에 담아낸다.',
      ],
      tips: [
        '밀가루를 충분히 볶아야 날내가 나지 않는다.',
        '농도가 되직하면 우유로 조절한다.',
      ],
    },
    ingredients: [
      { name: '양송이버섯', quantity: 200, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '우유', quantity: 300, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '생크림', quantity: 100, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '밀가루', quantity: 2, unit: '큰술', category: 'grain', pantryStaple: false },
      { name: '버터', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-chicken-steak',
    name: '치킨 스테이크',
    cuisine: 'WS',
    type: 'home',
    description: '겉은 바삭하게 구운 닭다리살 스테이크.',
    difficulty: 'easy',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 640,
    tags: ['치킨', '스테이크', '구이'],
    recipe: {
      steps: [
        '1. 닭다리살을 펼쳐 소금, 후추, 다진 마늘로 밑간한다.',
        '2. 팬에 식용유를 두르고 껍질 면부터 노릇하게 굽는다.',
        '3. 뒤집어 속까지 익히고 버터를 넣어 풍미를 더한다.',
        '4. 곁들일 채소를 같은 팬에 볶는다.',
        '5. 한입 크기로 썰어 접시에 담아낸다.',
      ],
      tips: [
        '껍질 면을 눌러가며 구우면 바삭해진다.',
        '두꺼운 부분은 칼집을 내면 고르게 익는다.',
      ],
    },
    ingredients: [
      { name: '닭다리살', quantity: 400, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '마늘', quantity: 3, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '브로콜리', quantity: 100, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '버터', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-shrimp-pilaf',
    name: '새우 필라프',
    cuisine: 'WS',
    type: 'home',
    description: '버터에 볶은 쌀과 새우로 만든 고소한 필라프.',
    difficulty: 'medium',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 580,
    tags: ['필라프', '새우', '볶음밥'],
    recipe: {
      steps: [
        '1. 양파, 당근, 파프리카를 잘게 다진다.',
        '2. 팬에 버터를 녹여 새우를 살짝 익혀 꺼낸다.',
        '3. 같은 팬에 채소를 볶다가 씻은 쌀을 넣어 볶는다.',
        '4. 채수를 붓고 뚜껑을 덮어 약불에서 쌀을 익힌다.',
        '5. 새우를 다시 넣고 섞어 소금, 후추로 간한다.',
      ],
      tips: [
        '쌀을 버터에 충분히 볶아야 고슬고슬해진다.',
        '육수는 쌀과 1:1 비율로 맞춘다.',
      ],
    },
    ingredients: [
      { name: '쌀', quantity: 1, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '새우살', quantity: 150, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '파프리카', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '채소 육수', quantity: 200, unit: 'ml', category: 'seasoning', pantryStaple: false },
      { name: '버터', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-potato-gnocchi',
    name: '감자 뇨끼',
    cuisine: 'WS',
    type: 'home',
    description: '쫀득한 감자 반죽을 토마토 소스에 버무린 뇨끼.',
    difficulty: 'hard',
    cookTimeMin: 60,
    servings: 2,
    estimatedCalories: 560,
    tags: ['뇨끼', '감자', '수제'],
    recipe: {
      steps: [
        '1. 감자를 삶아 뜨거울 때 곱게 으깬다.',
        '2. 밀가루, 달걀, 소금을 넣어 반죽한다.',
        '3. 반죽을 길게 밀어 한입 크기로 잘라 포크로 무늬를 낸다.',
        '4. 끓는 물에 넣어 떠오르면 건진다.',
        '5. 토마토 소스에 버무리고 파르메산 치즈를 뿌린다.',
      ],
      tips: [
        '밀가루를 너무 많이 넣으면 질겨지니 최소한만 넣는다.',
        '감자는 물기가 적은 분질 감자가 좋다.',
      ],
    },
    ingredients: [
      { name: '감자', quantity: 4, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '밀가루', quantity: 1, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '달걀', quantity: 1, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '토마토 소스', quantity: 250, unit: 'g', category: 'seasoning', pantryStaple: false },
      { name: '파르메산 치즈', quantity: 30, unit: 'g', category: 'dairy', pantryStaple: false },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-margherita-pizza',
    name: '마르게리타 피자',
    cuisine: 'WS',
    type: 'home',
    description: '토마토, 모차렐라, 바질의 클래식 이탈리아 피자.',
    difficulty: 'medium',
    cookTimeMin: 40,
    servings: 2,
    estimatedCalories: 720,
    tags: ['피자', '치즈', '오븐'],
    recipe: {
      steps: [
        '1. 피자 도우를 둥글게 펴서 도우판을 만든다.',
        '2. 토마토 소스를 얇게 바른다.',
        '3. 모차렐라 치즈를 고르게 올린다.',
        '4. 220도로 예열한 오븐에서 12분간 굽는다.',
        '5. 바질 잎과 올리브유를 뿌려 마무리한다.',
      ],
      tips: [
        '오븐을 충분히 예열해야 도우가 바삭해진다.',
        '치즈는 끝까지 채우지 말고 가장자리를 남긴다.',
      ],
    },
    ingredients: [
      { name: '피자 도우', quantity: 1, unit: '개', category: 'grain', pantryStaple: false },
      { name: '토마토 소스', quantity: 100, unit: 'g', category: 'seasoning', pantryStaple: false },
      { name: '모차렐라 치즈', quantity: 150, unit: 'g', category: 'dairy', pantryStaple: false },
      { name: '바질', quantity: 1, unit: '약간', category: 'vegetable', pantryStaple: false },
      { name: '올리브유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-bacon-carbonara',
    name: '베이컨 까르보나라',
    cuisine: 'WS',
    type: 'home',
    description: '달걀 노른자와 치즈로 만든 정통 까르보나라.',
    difficulty: 'medium',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 730,
    tags: ['파스타', '까르보나라', '달걀'],
    recipe: {
      steps: [
        '1. 스파게티를 소금 넣은 물에 8분간 삶는다.',
        '2. 볼에 달걀 노른자, 파르메산 치즈, 후추를 섞어 소스를 만든다.',
        '3. 팬에 베이컨을 바삭하게 굽는다.',
        '4. 불을 끄고 삶은 면과 면수를 넣어 섞는다.',
        '5. 달걀 소스를 부어 잔열로 빠르게 버무린다.',
      ],
      tips: [
        '불을 끄고 소스를 넣어야 달걀이 익어 덩어리지지 않는다.',
        '면수의 전분이 소스를 부드럽게 만든다.',
      ],
    },
    ingredients: [
      { name: '스파게티 면', quantity: 200, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '베이컨', quantity: 100, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '달걀 노른자', quantity: 2, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '파르메산 치즈', quantity: 40, unit: 'g', category: 'dairy', pantryStaple: false },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-cheese-omelette',
    name: '치즈 오믈렛',
    cuisine: 'WS',
    type: 'home',
    description: '체다 치즈를 듬뿍 넣어 말아낸 진한 오믈렛.',
    difficulty: 'easy',
    cookTimeMin: 15,
    servings: 2,
    estimatedCalories: 410,
    tags: ['오믈렛', '치즈', '달걀'],
    recipe: {
      steps: [
        '1. 달걀을 풀고 우유, 소금, 후추를 섞는다.',
        '2. 팬에 버터를 녹이고 달걀물을 붓는다.',
        '3. 가장자리가 익으면 체다 치즈를 가운데에 올린다.',
        '4. 양쪽을 접어 치즈를 감싼다.',
        '5. 접시에 담아 따뜻할 때 낸다.',
      ],
      tips: [
        '치즈는 미리 실온에 두면 잘 녹는다.',
        '약불에서 천천히 익혀야 겉이 타지 않는다.',
      ],
    },
    ingredients: [
      { name: '달걀', quantity: 4, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '체다 치즈', quantity: 2, unit: '장', category: 'dairy', pantryStaple: false },
      { name: '우유', quantity: 2, unit: '큰술', category: 'dairy', pantryStaple: false },
      { name: '버터', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-pumpkin-soup',
    name: '단호박 수프',
    cuisine: 'WS',
    type: 'home',
    description: '달콤한 단호박을 곱게 갈아 끓인 부드러운 수프.',
    difficulty: 'easy',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 340,
    tags: ['수프', '단호박', '건강식'],
    recipe: {
      steps: [
        '1. 단호박을 쪄서 껍질을 벗기고 속을 파낸다.',
        '2. 양파를 버터에 볶아 단맛을 낸다.',
        '3. 단호박, 양파, 우유를 넣고 끓인다.',
        '4. 핸드블렌더로 곱게 갈아준다.',
        '5. 생크림을 두르고 소금으로 간한다.',
      ],
      tips: [
        '단호박은 전자레인지에 살짝 돌리면 자르기 쉽다.',
        '농도는 우유나 육수로 조절한다.',
      ],
    },
    ingredients: [
      { name: '단호박', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '우유', quantity: 300, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '생크림', quantity: 50, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '버터', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-rose-pasta',
    name: '로제 파스타',
    cuisine: 'WS',
    type: 'home',
    description: '토마토와 크림을 섞어 부드럽고 진한 로제 파스타.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 660,
    tags: ['파스타', '로제', '크림'],
    recipe: {
      steps: [
        '1. 펜네를 소금 넣은 물에 9분간 삶는다.',
        '2. 팬에 올리브유를 두르고 다진 마늘과 양파를 볶는다.',
        '3. 토마토 소스를 넣어 졸인 뒤 생크림을 부어 섞는다.',
        '4. 삶은 면을 넣어 소스와 버무린다.',
        '5. 파르메산 치즈와 후추로 마무리한다.',
      ],
      tips: [
        '토마토와 크림은 2:1 비율이 균형이 좋다.',
        '약불에서 졸여야 소스가 분리되지 않는다.',
      ],
    },
    ingredients: [
      { name: '펜네 면', quantity: 200, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '토마토 소스', quantity: 200, unit: 'g', category: 'seasoning', pantryStaple: false },
      { name: '생크림', quantity: 100, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '마늘', quantity: 3, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '파르메산 치즈', quantity: 20, unit: 'g', category: 'dairy', pantryStaple: false },
      { name: '올리브유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-caprese-salad',
    name: '카프레제 샐러드',
    cuisine: 'WS',
    type: 'home',
    description: '토마토와 생모차렐라, 바질의 산뜻한 이탈리아 샐러드.',
    difficulty: 'easy',
    cookTimeMin: 10,
    servings: 2,
    estimatedCalories: 300,
    tags: ['샐러드', '토마토', '치즈'],
    recipe: {
      steps: [
        '1. 토마토를 도톰하게 슬라이스한다.',
        '2. 생모차렐라도 같은 두께로 썬다.',
        '3. 접시에 토마토와 치즈를 번갈아 올린다.',
        '4. 바질 잎을 사이사이에 끼운다.',
        '5. 올리브유와 발사믹, 소금, 후추를 뿌린다.',
      ],
      tips: [
        '잘 익은 토마토를 쓰면 단맛이 살아난다.',
        '먹기 직전에 드레싱을 뿌려야 신선하다.',
      ],
    },
    ingredients: [
      { name: '토마토', quantity: 2, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '생모차렐라 치즈', quantity: 125, unit: 'g', category: 'dairy', pantryStaple: false },
      { name: '바질', quantity: 1, unit: '약간', category: 'vegetable', pantryStaple: false },
      { name: '발사믹 식초', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '올리브유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-seafood-risotto',
    name: '해산물 리조또',
    cuisine: 'WS',
    type: 'home',
    description: '새우와 오징어를 넣어 감칠맛 가득한 해산물 리조또.',
    difficulty: 'hard',
    cookTimeMin: 40,
    servings: 2,
    estimatedCalories: 600,
    tags: ['리조또', '해산물', '쌀'],
    recipe: {
      steps: [
        '1. 새우와 오징어를 손질해 한입 크기로 썬다.',
        '2. 올리브유에 마늘과 양파를 볶아 향을 낸다.',
        '3. 쌀을 넣어 볶다가 화이트와인을 부어 졸인다.',
        '4. 따뜻한 해물 육수를 한 국자씩 부어가며 익힌다.',
        '5. 해산물을 넣어 익히고 소금, 후추로 간한다.',
      ],
      tips: [
        '해산물은 마지막에 넣어야 질겨지지 않는다.',
        '육수는 따뜻하게 유지해야 쌀이 고르게 익는다.',
      ],
    },
    ingredients: [
      { name: '쌀', quantity: 1, unit: '컵', category: 'grain', pantryStaple: false },
      { name: '새우살', quantity: 100, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '오징어', quantity: 100, unit: 'g', category: 'seafood', pantryStaple: false },
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '마늘', quantity: 2, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '화이트와인', quantity: 50, unit: 'ml', category: 'seasoning', pantryStaple: false },
      { name: '해물 육수', quantity: 600, unit: 'ml', category: 'seasoning', pantryStaple: false },
      { name: '올리브유', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-pork-cutlet',
    name: '폭찹',
    cuisine: 'WS',
    type: 'home',
    description: '두툼한 돼지 등심을 구워 소스를 곁들인 폭찹.',
    difficulty: 'medium',
    cookTimeMin: 30,
    servings: 2,
    estimatedCalories: 690,
    tags: ['돼지고기', '구이', '폭찹'],
    recipe: {
      steps: [
        '1. 돼지 등심에 소금, 후추, 다진 마늘로 밑간한다.',
        '2. 달군 팬에 식용유를 두르고 양면을 노릇하게 굽는다.',
        '3. 버터와 로즈마리를 넣어 향을 입힌다.',
        '4. 케첩, 우스터소스, 꿀을 졸여 소스를 만든다.',
        '5. 구운 고기에 소스를 끼얹어 낸다.',
      ],
      tips: [
        '두꺼운 고기는 약불에서 속까지 익힌다.',
        '굽기 전 칼집을 내면 수축을 막는다.',
      ],
    },
    ingredients: [
      { name: '돼지 등심', quantity: 400, unit: 'g', category: 'meat', pantryStaple: false },
      { name: '마늘', quantity: 3, unit: '쪽', category: 'vegetable', pantryStaple: false },
      { name: '로즈마리', quantity: 1, unit: '약간', category: 'vegetable', pantryStaple: false },
      { name: '케첩', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '우스터소스', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '꿀', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '버터', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '식용유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-mac-and-cheese',
    name: '맥앤치즈',
    cuisine: 'WS',
    type: 'home',
    description: '진한 치즈 소스에 마카로니를 버무린 미국식 별미.',
    difficulty: 'easy',
    cookTimeMin: 25,
    servings: 2,
    estimatedCalories: 710,
    tags: ['치즈', '마카로니', '면'],
    recipe: {
      steps: [
        '1. 마카로니를 소금 넣은 물에 8분간 삶는다.',
        '2. 냄비에 버터를 녹이고 밀가루를 볶아 루를 만든다.',
        '3. 우유를 조금씩 부어가며 베샤멜 소스를 만든다.',
        '4. 체다 치즈를 넣어 녹이고 소금, 후추로 간한다.',
        '5. 삶은 마카로니를 넣어 버무린다.',
      ],
      tips: [
        '우유는 데워서 넣으면 덩어리가 생기지 않는다.',
        '치즈는 불을 줄인 뒤 넣어야 부드럽게 녹는다.',
      ],
    },
    ingredients: [
      { name: '마카로니', quantity: 180, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '체다 치즈', quantity: 120, unit: 'g', category: 'dairy', pantryStaple: false },
      { name: '우유', quantity: 300, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '밀가루', quantity: 2, unit: '큰술', category: 'grain', pantryStaple: false },
      { name: '버터', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-spinach-gratin',
    name: '시금치 그라탕',
    cuisine: 'WS',
    type: 'home',
    description: '시금치와 베샤멜 소스를 치즈에 구워낸 그라탕.',
    difficulty: 'medium',
    cookTimeMin: 40,
    servings: 2,
    estimatedCalories: 480,
    tags: ['그라탕', '시금치', '오븐'],
    recipe: {
      steps: [
        '1. 시금치를 데쳐 물기를 짜고 송송 썬다.',
        '2. 버터에 밀가루를 볶고 우유를 부어 베샤멜 소스를 만든다.',
        '3. 시금치와 소스를 섞어 간한다.',
        '4. 내열 그릇에 담고 모차렐라 치즈를 올린다.',
        '5. 200도 오븐에서 15분간 노릇하게 굽는다.',
      ],
      tips: [
        '시금치 물기를 충분히 짜야 소스가 묽어지지 않는다.',
        '윗면에 빵가루를 뿌리면 바삭함이 더해진다.',
      ],
    },
    ingredients: [
      { name: '시금치', quantity: 200, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '우유', quantity: 250, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '모차렐라 치즈', quantity: 100, unit: 'g', category: 'dairy', pantryStaple: false },
      { name: '밀가루', quantity: 2, unit: '큰술', category: 'grain', pantryStaple: false },
      { name: '버터', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-french-toast',
    name: '프렌치 토스트',
    cuisine: 'WS',
    type: 'home',
    description: '달걀물에 적신 식빵을 노릇하게 구운 브런치 메뉴.',
    difficulty: 'easy',
    cookTimeMin: 20,
    servings: 2,
    estimatedCalories: 450,
    tags: ['브런치', '식빵', '달걀'],
    recipe: {
      steps: [
        '1. 달걀, 우유, 설탕을 섞어 달걀물을 만든다.',
        '2. 식빵을 달걀물에 충분히 적신다.',
        '3. 팬에 버터를 녹이고 약불에서 양면을 굽는다.',
        '4. 노릇해지면 접시에 담는다.',
        '5. 메이플 시럽과 슈가파우더를 뿌려 낸다.',
      ],
      tips: [
        '식빵을 살짝 묵힌 것을 쓰면 더 잘 스며든다.',
        '약불에서 천천히 구워야 속까지 익는다.',
      ],
    },
    ingredients: [
      { name: '식빵', quantity: 4, unit: '장', category: 'grain', pantryStaple: false },
      { name: '달걀', quantity: 2, unit: '개', category: 'dairy', pantryStaple: false },
      { name: '우유', quantity: 100, unit: 'ml', category: 'dairy', pantryStaple: false },
      { name: '메이플 시럽', quantity: 2, unit: '큰술', category: 'seasoning', pantryStaple: false },
      { name: '버터', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '설탕', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
    ],
  },
  {
    id: 'ws-minestrone-soup',
    name: '미네스트로네 수프',
    cuisine: 'WS',
    type: 'home',
    description: '여러 채소와 콩을 넣어 푸짐하게 끓인 이탈리아식 수프.',
    difficulty: 'easy',
    cookTimeMin: 35,
    servings: 2,
    estimatedCalories: 320,
    tags: ['수프', '채소', '토마토'],
    recipe: {
      steps: [
        '1. 양파, 당근, 셀러리, 감자를 깍둑썬다.',
        '2. 올리브유에 채소를 볶아 숨을 죽인다.',
        '3. 토마토 소스와 채소 육수를 붓고 끓인다.',
        '4. 강낭콩과 마카로니를 넣어 익힌다.',
        '5. 소금, 후추로 간하고 그릇에 담는다.',
      ],
      tips: [
        '채소는 비슷한 크기로 썰어야 고르게 익는다.',
        '하루 지나면 맛이 더 깊어진다.',
      ],
    },
    ingredients: [
      { name: '양파', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '당근', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '셀러리', quantity: 1, unit: '대', category: 'vegetable', pantryStaple: false },
      { name: '감자', quantity: 1, unit: '개', category: 'vegetable', pantryStaple: false },
      { name: '강낭콩', quantity: 80, unit: 'g', category: 'vegetable', pantryStaple: false },
      { name: '마카로니', quantity: 50, unit: 'g', category: 'grain', pantryStaple: false },
      { name: '토마토 소스', quantity: 200, unit: 'g', category: 'seasoning', pantryStaple: false },
      { name: '채소 육수', quantity: 500, unit: 'ml', category: 'seasoning', pantryStaple: false },
      { name: '올리브유', quantity: 1, unit: '큰술', category: 'seasoning', pantryStaple: true },
      { name: '소금', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
      { name: '후추', quantity: 1, unit: '약간', category: 'seasoning', pantryStaple: true },
    ],
  },
];
